### PR TITLE
Proposal of package kb2999226

### PR DESCRIPTION
**Pull request by RedBaron2**
@gep13 
A member on the gitter channel still really needs this package as a dependency for their package. This package was not in the chocolatey community feed. It has been tested and works. It will install the KB if not already installed, and skips install if already installed. Since it is a Microsoft KB no uninstaller in needed. The package should not need updating because it is static. Thank you for considering this package for the community feed.

### CODE REVIEW

**Comment by majkinetor** [comment]
One note: Get-HotFix is Powershell 3+ functions, and packages should work with Powershell2. As it is, this package wont work on vanilla Windows 7.

**Comment by AdmiringWorm** [comment]
another note is, this update requires [kb2919355](https://chocolatey.org/packages/KB2919355) which is available on chocolatey.

**Comment by gep13** [comment]
>@majkinetor said...
One note: Get-HotFix is Powershell 3+ functions, and packages should work with Powershell2. As it is, this package wont work on vanilla Windows 7.

Did you test this?

I have just ran this:

```
powershell -Version 2.0 Get-HotFix -id "kb2999226" -ErrorAction SilentlyContinue
```

and it output suggested that it works:

```
Source        Description      HotFixID      InstalledBy          InstalledOn
------        -----------      --------      -----------          -----------
MINTLAW       Update           KB2999226     NT AUTHORITY\SYSTEM  10/07/2015...
```

I don't have a vanilla Windows 7 machine to run on, but assuming that specifying the PowerShell Version Number works as I expect it does, then the Get-HotFix cmdlet works on Version 2.0.

**Comment by majkinetor** [comment]
No I didn't. I just checked online. And you are right.

**Comment by gep13** [comment]
>@majkinetor said...
No I didn't. I just checked online. And you are right.

Cool. Thanks for checking 😄 

So, assuming that we add a dependency on kb2919355, this one should be good to go, right?  If so, I can push it just now, as I am away to work on a few things.

**Comment by gep13** [comment]
@AdmiringWorm while I see you online...

You ok with the above?

**Comment by AdmiringWorm** [comment]
@gep13 with the exception of missing a dependecy for KB2919355, I'm all ok with it.
But I don't really know how to handle MSU updates on chocolatey, so I may not be the
correct person to ask though.

**Comment by RedBaron2** [comment]
Just a note the kb is only for windows 7 with Service Pack 1 not vanilla.

**Comment by gep13** [comment]
@RedBaron2 I have made some adjustments to the PR that you sent through, and have merged it into master.  The package is now in the moderation queue: https://chocolatey.org/packages/kb2999226

Thanks again!

**Comment by ferventcoder** [comment]
@gep13 did you make adjustments so this package does not error when a platform is not supported?

**Comment by jberezanski** [comment]
@majkinetor 

> One note: Get-HotFix is Powershell 3+ functions, and packages should work with Powershell2.

You were probably following the [TechNet documentation for Get-HotFix](https://technet.microsoft.com/en-us/library/hh849836(v=wps.620).aspx). The catch is that Microsoft has removed the docs for PowerShell versions older than 3.0, so the lack of "PowerShell 2.0" in the version selection combo box is not conclusive.

Archive.org to the rescue: https://web.archive.org/web/20090830212640/http://technet.microsoft.com/en-us/library/dd315358.aspx

**Comment by gep13** [comment]
>@jberezanski said...
The catch is that Microsoft has removed the docs for PowerShell versions older than 3.0

WTF! Why would they do that?!?

**Comment by jberezanski** [comment]
Bill^H^H^H^HSatya knows... Perhaps as a subtle message "you should stop using this" ;-). They have also taken down several old, but useful KB articles and downloads (even some still referenced by their other docs). A royal PITA, for sure.

Fortunately, .NET docs still go as far back as 1.1. We should count our blessings, I suppose.

**Comment by gep13** [comment]
>@jberezanski said...
We should count our blessings, I suppose.

Ha ha, fair point 😄

**Comment by majkinetor** [comment]
@jberezanski , you are totally right, thats what I did. Thanks for clarification.

**Comment by ferventcoder** [comment]
They took down 2.0 a LONG time ago. Usually the v3 tells you whether it was introduced in v3 or not.

**Pull request merged**
