### PR TITLE
(poweriso) Changed to get the actual URL during install

### PR DESCRIPTION
**Pull request by AdmiringWorm**
I know it isn't optimal, but this was the only way I found that we could get the correct installer.
So unless someone gets the redistribution rights from the poweriso team, this I believe will have to do.

@gep13 @majkinetor 
could you guys test the install script, without changing the hash.

### CODE REVIEW

**Comment by majkinetor** [comment]
Works OK.

```
poweriso~> Test-Package
Nuspec file given, running choco pack
Attempting to build package from 'poweriso.nuspec'.
Successfully created package 'C:\work\_chocolatey\chocolatey-coreteampackages\automatic\poweriso\poweriso.6.7.0.20161216.nupkg'

Package info
  Path:         C:\work\_chocolatey\chocolatey-coreteampackages\automatic\poweriso\poweriso.6.7.0.20161216.nupkg
  Name:         poweriso
  Version:      6.7.0.20161216
  Vagrant:      c:\work\_chocolatey\chocolatey-test-environment

Testing package using vagrant
Removing existing vagrant packages
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ferventcoder/win2012r2-x64-nocm' is up to date...
==> default: There was a problem while downloading the metadata for your box
==> default: to check for updates. This is not an error, since it is usually due
==> default: to temporary network problems. This is just a warning. The problem
==> default: encountered was:
==> default:
...
...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: shell/TestPackages.ps1 as c:\tmp\vagrant-shell.ps1
==> default: ============================================================
==> default: TESTING FOLLOWING PACKAGES: poweriso:6.7.0.20161216
==> default:
==> default: ============================================================
==> default:
==> default: ------------------------------------------------------------
==> default: PACKAGE: poweriso:6.7.0.20161216
==> default: OPTIONS: c:\packages\poweriso.6.7.0.20161216.xml
==> default: Name                           Value
==> default: ----                           -----
==> default: Install                        True
==> default: Uninstall                      False
==> default: Parameters
==> default: ------------------------------------------------------------
==> default: TESTING INSTALL FOR poweriso:6.7.0.20161216
==> default: CMD: choco install -fy poweriso --allow-downgrade --version 6.7.0.20161216 --source "'c:\packages;http://chocolatey.org/api/v2/'"
==> default: Chocolatey v0.10.3
==> default: Installing the following packages:
==> default:
==> default: poweriso
==> default: By installing you accept licenses for the packages.
==> default: poweriso v6.7.0.20161216 (forced)
==> default: poweriso package files install completed. Performing other installation steps.
==> default: Using system proxy server '10.35.9.55:8080'.
==> default: Could not find a part of the path 'C:\Users\Administrator\AppData\Local\Temp\chocolatey\poweriso\6.7.0.20161216\qt4ojyeo.zoj.istext'.
==> default: Download of qt4ojyeo.zoj (-1 B) completed.
==> default: Downloading poweriso 64 bit
==> default:
==> default:   from 'http://www.worldnowclear.com/D4_4xGdve9W4JoaQK7O9aFTBXwk5C73QQAl_N3mNEfpiJDcgMn4wOTKxEOiHG7uSpzvDXUSZuzUe8K455DP7m+GyKBn69FHBUtuAafq_e5SoB0uRThgJlujRBXYVnK+VyZKts_CDtHrEGe8y3O0EfzoiobrL6w==-G1EAAGTcXGs0k8TI8vu6O2zAgVOZBGQD4LAxdq7gcRc1FhTqzuEX4o7biytTqARslx9zQihkSqhKQK0oVUTpsQLTzs3nP3OCeT_711A='
==> default: Download of powerisoInstall.exe (3.68 MB) completed.
==> default: Hashes match.
==> default: Installing poweriso...
==> default: poweriso has been installed.
==> default: Only an exit code of non-zero will fail the package by default. Set
==> default:  `--failonstderr` if you want error messages to also fail a script. See
==> default:  `choco -h` for details.
==> default:  The install of poweriso was successful.
==> default:
==> default:   Software installed to 'C:\Program Files\PowerISO'
==> default: Chocolatey installed 1/1 packages. 0 packages failed.
==> default:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
==> default: Exit code for poweriso:6.7.0.20161216 was 0

==> default: Running provisioner: shell...
    default: Running: User.ps1 as c:\tmp\vagrant-shell.ps1
==> default: User script can be added in User.ps1
==> default: SUCCESS: Specified value was saved.
==> default: Testing package if a line is uncommented.
==> default:
==> default: Exit code was 0

```
Junk tool tho, it requrest you to wait few seconds before start, brings IE with thank you, etc... I can't wait to unlist it :dagger:

**Comment by majkinetor** [comment]
BTW, 

```
Could not find a part of the path 'C:\Users\Administrator\AppData\Local\Temp\chocolatey\poweriso\6.7.0.20161216\qt4ojyeo.zoj.istext'.
```

is really anoying all around, that should be fixed.

**Comment by AdmiringWorm** [comment]
> Junk tool tho, it requrest you to wait few seconds before start, brings IE with thank you, etc... I can't wait to unlist it

I remember it was quite good back in the day, but it's been years since I've used it.

> is really anoying all around, that should be fixed in core.

Yeah it really should, same as it should not use a temporary name, a user previously was confused by this and thought something was wrong.

I'm waiting with merging this though, until after I've heard from @gep13  since he is the original maintainer of the package.

**Comment by majkinetor** [comment]
I think ultraiso is way better in conmercial world.

**Pull request merged**
