### PR TITLE
(new package) eclipse

### PR DESCRIPTION
**Pull request by 030**

### CODE REVIEW

**Comment by gep13** [comment]
Relates to #256

**Comment by gep13** [comment]
@030 I thought your packages were automatic packages?  This is not a problem if not, I just thought that the main problem that you had was that you didn't have a windows server to run ketarin in order to continue automatically pushing the packages.

Also, with regard to your common functions, I think that it might be better to include them as an extension package, and then take a dependency on that package, rather than dot sourcing them.  That way, if anything changes in one of those files, you can push out a new version of the extension package, without touching the actual package itself.  You can see examples of these in the extensions folder in this repository.

**Comment by gep13** [comment]
@030 did you happen to see my comment above?  Thanks!

**Comment by majkinetor** [comment]
I think we should close this as there is no feedback.

**Comment by gep13** [comment]
Agreed

**Pull request closed without merging**
