### PR TITLE
Update chocolateyInstall.ps1

### PR DESCRIPTION
**Pull request by RedBaron2**
This is a proposed change of the install ps1 file.
This should install System Level if the Chromium key is present, and %appdata% if that key is present.
Everything checks as far as Power Shell is concerned < fingers crossed >

### CODE REVIEW

**Comment by gep13** [comment]
@RedBaron2 is there a reason that you have created your own function for Get-Level and Get-ProcessorBits?

**Comment by RedBaron2** [comment]
Didn't know that Chocolatey had these functions; They can be removed if they conflict with chocolatey.

**Comment by gep13** [comment]
Yes, these type of functions do exist already.

Have a look here:

https://github.com/chocolatey/chocolatey-coreteampackages/blob/765885000ca097b5628e3e41fbaa27638d35cc93/automatic/fiddler4/tools/chocolateyUninstall.ps1#L6

As an example.

Can you re-work this PR to use these?  Thanks!

**Comment by RedBaron2** [comment]
@gep13  Changed the file to use Chocolatey functions. Thanks for the push in the right direction. I do have a question about if a bit of code will work

`$file = (Get-ItemProperty -Path $hk_level":\"

If this works than I will have a uninstall file for chromium. The main question is if the variable needs to be in the quote?

**Comment by RedBaron2** [comment]
@gep13  Made a cleanup change to the file, and have submitted #259 to make a few Chocolatey Users happy. The main push has been the whole hkcu vs hklm issue of the package. Some Users don't have a problem with the package being just for them, and others want the package to be for the whole (system level). This file will test for the hkcu key and if set will install for that user, and vice versa.

**Comment by RedBaron2** [comment]
@gep13 Took out the functions that may have been a bottleneck and streamlined the file. Thanks for taking your time in committing this to the actual.

**Comment by RedBaron2** [comment]
@gep13 Tested and confirmed working; Condensed the code some more; Thanks for being reserved in merging this file.

**Comment by gep13** [comment]
@RedBaron2 sorry for taking so long to get back to you about this.

I am going to go ahead and merge this.  Thanks!

**Comment by RedBaron2** [comment]
@gep13 Thanks, we will see how this works out.

**Pull request merged**
