### PR TITLE
Update chromium.nuspec

### PR DESCRIPTION
**Pull request by RedBaron2**
Changed Continuous to Snapshots

### CODE REVIEW

**Comment by gep13** [comment]
@RedBaron2 thank you for making this change.  Looks like all the line endings have changed in this line, rather than just the title.  Would it be possible for you to correct this?  Thanks!

**Comment by RedBaron2** [comment]
I hope that Commit 1b1f863c0d31706007499dce84384ff36a2d6400 is better, I don't know why it did all the lines changing bit.
Thanks

**Comment by gep13** [comment]
Yes, that looks better, thanks!

**Comment by gep13** [comment]
@RedBaron2 thanks for your contribution! :+1:

**Pull request merged**
