### PR TITLE
New package: UltraDefrag

### PR DESCRIPTION
**Pull request by Redsandro**
It took me way too long to push the update to 6.0.4 while people where bugging me about it.
I hadn't converted it to an autopackage (for myself) yet, so I hope I remembered how to do it properly for the core team packages.

### CODE REVIEW

**Comment by Redsandro** [comment]
I'm very sorry but someone has to fix that icon. I thought I did it properly, even added a CDN link at the bottom of the README as a selfnote. But it doesn't link to the commit; it links to the branch. And that won't work because the branch can be removed after merge with master, and I'm guessing the CDN for the branch is gone then, too. (Not tested tho. :P)

This is exactly what I mean when I disagreed with making things even the slightest bit complicated in issue https://github.com/chocolatey/chocolatey-coreteampackages/issues/20#issuecomment-64937878

I haven't contributed in a few weeks and I forgot those little hacks. I don't feel like digging through wiki's to figure out how to do it, and I rediscovered that this method is a hoop people have to jump through to commit. __#dontlike__

**Comment by Redsandro** [comment]
sooo....

**Comment by TomOne** [comment]
@Redsandro, is `ultradefrag-beta` meant as separate package?

If that is the case, move it to a separate folder to match the directory structure of the rest of the packages.

**Comment by Redsandro** [comment]
It's not, it's meant for (manually) publishing a "pre-release" version of the same package.

UltraDefrag puts out pre-releases before a final version, but the problem is that, unlike the main version, the pre-releases don't have consistent (ketarinable) names. So this one time when it took a long time for a final version to be released, I just manually used the beta template for prereleases.

**Comment by Redsandro** [comment]
Guys, people are using this package. It would be nice to add it to the ketarin machine.

https://github.com/Redsandro/chocolatey/pull/15

**Comment by cfoellmann** [comment]
:+1: would love to see this merged to let me rebase my improvements on this

**Comment by Redsandro** [comment]
@cfoellmann this project is semi-dead. Some PRs are 6 months old and the relevant people haven't found the time or intention to verify and merge. That's their prerogative and I can very well imagine this because I'm not exactly fast with fixes myself.

But I'd love to see this updated; do you care to take over as maintainer? If you give me your chocolatey name I will add you as maintainer.

**Comment by cfoellmann** [comment]
sure. I will be happy to help you maintain the package and keep bugging the core team :imp: 
My Chocolatey username is also `cfoellmann`.

**Comment by Redsandro** [comment]
@cfoellmann it is done. Take it or leave it. :smile: 
And let me know if you are interested in maintaining any of these packages: https://github.com/chocolatey/chocolatey-coreteampackages/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3ARedsandro+label%3A%22Up+for+grabs%22+

**Comment by Redsandro** [comment]
This core team repo is very awesome in theory. There is a dedicated autopackage machine, the repo will survive even if your part of the planet gets hit by a meteorite, etcetera.

Hence, getting your code up here is something theoretically desirable.

**Comment by cfoellmann** [comment]
@ferventcoder What is the protocol here?
I have a nice improvement for the package https://github.com/Redsandro/chocolatey/pull/15 I think is necessary to make the package usable for adv users. is there any chance for this to get in?

**Comment by Redsandro** [comment]
@cfoellmann I could be wrong, but to my understanding there are (only) two people who can do what is necessary to get autopackages to run on the ketarin machine. They need to do the final merge and fixes. These people are, if I understand correctly, @gep13 and @TomOne. The idea was great, but they experienced it was too much effort to maintain (understandably so) and started ignoring pull requests since half a year ago.

I created a [script to clean up the ketarin exported settings](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/bin#preparing-settingsxml-for-this-repo) in order to make it easier for @gep13 and @TomOne to merge PRs in a way they want the settings, but it's still not enough.

It doesn't help that - subjectively and in my opinion - they are too particular on their package demands. When I created a PR from a virtual machine that has since been destroyed, I can't be bothered to change a package _that's already working_. It takes half an hour + for me to set up and clone the repo on a VM and 1 minute for them to implement these trivial changes.

---

We need more people to (quickly) merge packages to the ketarin machine, and we need a group of volunteers to fix broken autopackages. The model of one maintainer per package just doesn't work.

**Comment by Redsandro** [comment]
@cfoellmann I think - if you want - you should just host your own github repo for your package(s), create an (auto)package locally and push it to Chocolatey. I did add you as a maintainer.

If this repo gets resurrected to 3rd parties (it's not dead - latest commit was a month ago by @TomOne - it's just not watching PRs), you can transfer your local code to this repo. Perhaps @TomOne or @gep13 can add you as a repo member so you can work on the code in this repo.

**Comment by gep13** [comment]
I am not ignoring this thread, there are just a few other things ahead of it in the queue, but I will get to it.

**Comment by Redsandro** [comment]
This illustrates the pressure you guys are under. :smile:

**Comment by Redsandro** [comment]
Ok, because waiting for this long is literally fracking bullshot, here's what I did:

* I built the package using the ketarin (so package is fine)
* merged the package to master
* removed myself as a maintainer
* approved the package
* added myself as a maintainer again

Now please dear god @gep13 @TomOne @ferventcoder add `ultradefrag.ketarin.xml` to the ketarin machine.

**Comment by gep13** [comment]
Done.

Quick question, what is the `ultradefrag-prelease.ketarin.xml` file, and why do we need it?

**Comment by Redsandro** [comment]
> it's meant for (manually) publishing a "pre-release" version of the same package.
>
> UltraDefrag puts out pre-releases before a final version, but the problem is that, unlike the main version, the pre-releases don't have consistent (ketarinable) names. So this one time when it took a long time for a final version to be released, I just manually used the beta template for prereleases.

**Comment by gep13** [comment]
Ok, gotcha :+1:

**Comment by Redsandro** [comment]
Thanks! :+1:

**Pull request merged**
