### PR TITLE
Adds Windows kb2670838 - Platform update

### PR DESCRIPTION
**Pull request by matbech**
https://www.microsoft.com/en-us/download/details.aspx?id=36805

### CODE REVIEW

**Comment by jberezanski** [comment]
LGTM!
I wonder if AU will push a package which does not exist in the community repo yet...?

**Comment by gep13** [comment]
>@jberezanski said...
I wonder if AU will push a package which does not exist in the community repo yet...?

As long as the `chocolatey` user has been added as maintainer of the package, then I don't see why not 😄

**Comment by jberezanski** [comment]
There was no package on chocolatey.org yet, so there was nothing to add the `chocolatey` user to. This was a completely new package.

But... it worked :) https://chocolatey.org/packages/kb2670838

**Comment by gep13** [comment]
Ah, I see what you mean.  In which case yes, it is just a push of a new package, and will work in the same way as if doing it from your local machine, just uses the chocolatey user API key.

**Pull request merged**
