### PR TITLE
(sysinternals) fixed checksum

### PR DESCRIPTION
**Pull request by smithyuk**
Fixed checksum to prevent install failure + updated update.ps1 script

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
I'm afraid I'll have to deny this pull request.
Checksums are automatically generated by AU (the only thing we need to do is adding a empty commit with `[AU sysinternals]`.
There is also a change in this PR that shouldn't be here, there is a reason we have the `-ChecksumFor` set to `none`, the reason being a problem with one of the functions we use in the install script, so we need to generate the checksum using a powershell function instead (see the `global:au_BeforeUpdate` function).

I'll queue the update of sysinternals shortly though (just need to test that the checksum actually have changed).

**Comment by smithyuk** [comment]
No worries, thanks!

**Comment by AdmiringWorm** [comment]
I still appreciate you trying to help out though.

**Comment by AdmiringWorm** [comment]
The sysinternals package is going through the update process now, and should have passed the automated checks on chocolatey.org in a few hours.

**Pull request closed without merging**
