### PR TITLE
migrated and updated vcredist2017 from jberezanski

### PR DESCRIPTION
**Pull request by matbech**
migrated from https://github.com/jberezanski/ChocolateyPackages/tree/master/vcredist2017
version updated to 2017 RC

### CODE REVIEW

**Comment by gep13** [comment]
@matbech thanks for creating this PR.

@jberezanski this looks good to me, any objections to it being pulled into this repo?

**Comment by matbech** [comment]
@jberezanski I have migrated and updated your package: https://github.com/chocolatey/chocolatey-coreteampackages/pull/420
if you have a chance, please review it. You are also listed as the original author of the package (https://github.com/chocolatey/chocolatey-coreteampackages/pull/420/files#diff-50d53a1b1c571cbec982d31d1a068b4d) which should help with any future PRs. Finally, please add the "chocolatey" user to the list of maintainers in the package administration page. Thank you.

**Comment by jberezanski** [comment]
@matbech Thanks for updating this package.  I'm currently in the process of rebuilding my dev machine, so I'm lagging a bit behind in Chocolatey package support.

A few issues:
1) Since this installer still overwrites the redist from VC++ 2015 (thanks for [linking](https://github.com/chocolatey/chocolatey-coreteampackages/pull/406#issuecomment-263136039) to the [valuable comment by STL](https://news.ycombinator.com/item?id=12969425), by the way!), I'd like to keep the warning in the package description (perhaps with a slightly different wording, now that we know that this is intended behavior). Ultimately, I think both this package and `vcredist2015` should be reshaped into metapackages that would depend on appropriate versions of a new `vcredist140` package.
2) This is not RTM yet, so the package version should have a prerelease suffix ("-rc1", in this case).
3) I'd like to keep providing a short description of package changes in the release notes. "14.10.24629.0-rc1: First package release for Visual Studio 2017 RC" would work here, I think.
4) Does uninstallation work? Is the entry in Programs and Features actually named "Microsoft Visual C++ vNext Redistributable" now?

(Also, a hint for the future: this PR would be easier to review if you had first imported my code intact and then made your changes in a subsequent commit.)

Anyway, thanks for the PR. I hope I'm able to bring my machine online shortly, so that I'll be able to test this myself and work on building the new vcredist package.

**Comment by matbech** [comment]
@jberezanski 

>1 
I have added the warning back but as a note instead. I don't think we should scare away users from installing/upgrading the redistributable.

>2
Done

>3
I believe the package description is self-explaining. Future changes for the same package version should be documented though.

>4
Yes, that exact wording is in the uninstaller entry now. I expect it to be changed (again) in the final version.

I propose to merge this PR in the current state, so that it will be easier for you to do any other changes you wish to do.

**Comment by jberezanski** [comment]
Looks fine now, let's see if the automatic pushing machinery will work ;-)

**Comment by jberezanski** [comment]
...and [it's online](https://chocolatey.org/packages/vcredist2017/14.10.24629.0-rc1). Thanks again @matbech for the PR!

@majkinetor this AppVeyor automation stuff is really cool :)

**Comment by majkinetor** [comment]
@jberezanski , thx, it is cool :) Will be way cooler in the future if time permits.

**Pull request merged**
