### PR TITLE
(wixtoolset) add checksum to wix package

### PR DESCRIPTION
**Pull request by TerribleDev**
add checksum to the newest wix package....

I'm not sure what you will have to do to add this package since it already exists in chocolatey, but since this org is chocolatey I'm sure you can use super admin powerz

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
Hello, thanks for your contribution and I'm sorry about the delay in the review process.
Unfortunately another PR was opened that uses the latest version, as such this will be closed in favour of #647. 

Feel free to reopen if you disagree.

**Comment by AdmiringWorm** [comment]
nvm, noticed that the other PR is for the latest RC version

**Comment by gep13** [comment]
>@AdmiringWorm said...
Need to figure out how we are to update this before this is merged.

Can we not manually update version to package fix and then [AU PUSH]?

**Comment by AdmiringWorm** [comment]
@gep13 yes, that's exactly what needs to be done. I was waiting on #647 that included some updates to the install script before rebasing and merging this one.

**Comment by TerribleDev** [comment]
so long as 3.10.3.3007 is fixed I will be happy

**Comment by AdmiringWorm** [comment]
@TerribleDev it's going through moderation now, and will be available under the version `[.10.3.300701](https://chocolatey.org/packages/wixtoolset/3.10.3.300701) when moderation is complete.

**Comment by TerribleDev** [comment]
🤘 thanks!

**Pull request merged**
