### PR TITLE
(qbittorrent) Migrated to AU

### PR DESCRIPTION
**Pull request by AdmiringWorm**
### Other changes
* Added project source url
* Updated package source url
* Update Icon Url
* Changed package to use fosshub instead of sourceforge
* Changed directory name to be lower case

***NOTE: Really no need to force push the package unless a change from sourceforge url to fosshub is a priority***

### CODE REVIEW

**Comment by majkinetor** [comment]
LG2M . Thanks.

**Comment by AdmiringWorm** [comment]
Nemo problemo, still wonder how I managed to push it to a *package/thunderbird* branch though. Especially since I have no plans to even try migrating the thunderbird package.

**Comment by majkinetor** [comment]
Didn't see that... mistakes happen all the time, humans only :)

**Comment by gep13** [comment]
@AdmiringWorm quick question...

Did you test this out on the local test environment?  I am getting an error when I try to install it:

image

Seems the install went ok, and qbittorrent runs correctly.  Perhaps another valid exit code is required?

**Comment by gep13** [comment]
@AdmiringWorm yes, looks like that is what is required:

image

That exit code exists in the previous version.

**Comment by AdmiringWorm** [comment]
I did test it in local test environment and never got the error.
I don't know how I missed that second exit code, I'll add ASAP.

**Comment by gep13** [comment]
>@AdmiringWorm said...
I did test it in local test environment and never got the error.

Strange. Do you have the sandbox enabled?  I rollback every time before provisioning a new package.

>@AdmiringWorm said...
I don't know how I missed that second exit code, I'll add ASAP.

Not a problem at all.  Let me know when you are done, and I will merge this.

**Comment by AdmiringWorm** [comment]
>Strange. Do you have the sandbox enabled? I rollback every time before provisioning a new package.

Yes, I have sandbox enabled and I always rollback before provisioning a new package.
I tested it again in the test environment, and still get exit code 0
<https://gist.github.com/AdmiringWorm/b5a52b56a509e33493c36b46e650a8c6>
I'll still add the 1223 exit code though.

**Comment by gep13** [comment]
Hmm, that is very strange indeed!  What version of Chocolatey is your environment using?  Mine is running 0.10.2.

**Comment by AdmiringWorm** [comment]
It's running 0.10.3

**Comment by gep13** [comment]
Ooo, interesting...

**Comment by gep13** [comment]
Strange. Same thing with 0.10.3.  Not sure why we would be seeing different results.

@ferventcoder any ideas on why it would work differently between two instance of the local test environment?

**Comment by AdmiringWorm** [comment]
@gep13 maybe it just likes me better 😛

**Comment by gep13** [comment]
ha ha, maybe :-)

by the way, do you use Gitter? https://gitter.im/chocolatey_au/Lobby?at=57fd3d70d6251fd126ae4f15

**Pull request merged**
