### PR TITLE
Deleted _output temporary files clogging the repo.

### PR DESCRIPTION
**Pull request by Redsandro**
I think we should remove this ever growing cache of every version ever.

For those rare cases where you want to manually fix one specific package without keeping those fixes, you should just download the package and extract it, work on that.

Make git clone fast and efficient.

@TomOne @ferventcoder https://github.com/chocolatey/chocolatey-coreteampackages/commit/22aa143b76af703b16e10d139a597ed89f1d3a2a#commitcomment-9001191

### CODE REVIEW

**Comment by TomOne** [comment]
:+1: for this.

**Comment by Redsandro** [comment]
I say two upvotes and a maybe:

> _@ferventcoder said on december 16th 2014:_
Perhaps we don't need to save the output folder after all.

cause me to click that friendly green button that sais _Merge_.

Please forgive me.

**Comment by ferventcoder** [comment]
:)

**Comment by ferventcoder** [comment]
There's comedy all over here ;)

**Comment by gep13** [comment]
OMG!

I can't believe that you have deleted that folder!  I was very fond of it, we had some good times! :crying_cat_face:

**Comment by Redsandro** [comment]
Well think of it this way. _Merge_ sounds an awful lot like _Merde_ which is French for I love you.

**Comment by gep13** [comment]
> Merge sounds an awful lot like Merde which is French for I love you.

Ha ha! :-)

**Comment by Redsandro** [comment]
Is there some way we can squash the `master` history where we keep the icons but we squash the `_output` history into oblivion?

Because a `git clone` brings in about 5% of relevance and 95% of `_output` objects in git history.

(those statistics are made up but a git clone takes long, and I work on random computers so I always have to do a git clone in order to work on or add a package)

**Comment by ferventcoder** [comment]
@Redsandro what you may want instead is to do a `git clone --depth 1` - http://git-scm.com/docs/git-clone

This will give you what you need if you don't want the large history. There are ways to [delete](https://help.github.com/articles/remove-sensitive-data/) [files](http://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository) [from](http://stackoverflow.com/questions/307828/completely-remove-file-from-all-git-repository-commit-history) all history but it is very disruptive and shouldn't be done lightly.

**Comment by Redsandro** [comment]
¿ɟʇʍ I didn't know that! Sweet.

**Comment by ferventcoder** [comment]
Git can do almost anything, you just have to know what to tell it to do. :) 
https://importantshock.wordpress.com/2008/08/07/git-vs-mercurial/

**Comment by gep13** [comment]
:+1: on the use of ```depth```

**Comment by mwrock** [comment]
GIT just fed my dogs. It is truly awesome.

Sent from my Windows Phone
________________________________

**Comment by ferventcoder** [comment]
Git spends time with my wife and kids sometimes. It's the best babysitter.

**Comment by Redsandro** [comment]
I'm trying out git as a replacement girlfriend. On the terminal she's equally black and white.

```
git commit -am "`curl -s http://whatthecommit.com/index.txt`"
```

**Comment by gep13** [comment]
> I'm trying out git as a replacement girlfriend. On the terminal she's equally black and white.

ha ha! :smile_cat:

**Pull request merged**
