### PR TITLE
(sysinternals) Added support for nano server

### PR DESCRIPTION
**Pull request by AdmiringWorm**
Also removed duplicate urls/checksums that isn't needed.

Required to merge with `[AU sysinternals]` in the merge title

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
> Looks awesome.

Thanks, I'm not sure if choco even runs on nano servers though, but figured it couldn't hurt to add support for it in the package.

**Comment by majkinetor** [comment]
Choco will run on nano if it doesn't now.

**Comment by gep13** [comment]
It is on the road map, but doesn't work currently.

**Comment by AdmiringWorm** [comment]
@gep13 I see, well this is one package that don't need to be updated at least when choco supports nano servers

**Comment by gep13** [comment]
>@AdmiringWorm said...
this is one package that don't need to be updated at least when choco supports nano servers

Nice!  In order to support Nano, Chocolatey needs to be ported to run on .Net Core.

**Pull request merged**
