### PR TITLE
Added Update-IconUrl script

### PR DESCRIPTION
**Pull request by AdmiringWorm**
Added a script to easily update or add new icon url to nuspec files
Works for a single package, or passing without a name tries to update all packages which have an icon matching the package name.

### CODE REVIEW

**Comment by majkinetor** [comment]
Can you please add regular Powershell documentation ? 
Is it idempotent ?

Can it handle situation when package is moved over repository. If I, for example move my packages here, icons will point to my repository and {user}{repo} should be changed.

**Comment by AdmiringWorm** [comment]
> Can it handle situation when package is moved over repository. If I, for example move my packages here, icons will point to my repository and {user}{repo} should be changed.

@majkinetor with this script, it would require you to move the icons over as well.
then run `Update-IconUrl.ps1 "Insert Package Name"` which then searches for the
matching icon with the same name as the package, and updates the commit hash (committing the icon if it hasn't already) and updates the rawgit url with that commit has and the specified `GithubRepository` parameter (defaults to chocolatey/chocolatey-coreteampackages)

> Can you please add regular Powershell documentation ?

I'll look into trying to get some powershell documentation for this

**Comment by majkinetor** [comment]
Could you please add some examples, those are more telling then all the docs combined.

**Comment by AdmiringWorm** [comment]
@majkinetor something like that perhaps?

**Comment by majkinetor** [comment]
Thanks for the work. I will try it as soon as I can, if somebody bits me to it let us know here.

**Comment by AdmiringWorm** [comment]
ok, let me know if there is any problems, I'm still in the process of learning powershell so there is bound to be some hiccups

**Comment by gep13** [comment]
@AdmiringWorm going to go ahead and pull this in, so that we can take it for a spin, we can PR again if additional changes are required.

**Comment by AdmiringWorm** [comment]
sure thing

**Pull request merged**
