### PR TITLE
Fixed fosshub requiring referrer for downloads

### LINKED ISSUE #414: (fosshub.extension) Download URL within "xdts"-attribute
The package does no longer work for me because the download url of the binaries is stored within the xdts-attribute of the link now instead of the data-attribute.

https://github.com/chocolatey/chocolatey-coreteampackages/blob/e17820954cdce01bf1979a4ecaa7b7baa0612706/extensions/chocolatey-fosshub.extension/extensions/Get-UrlFromFosshub.psm1#L33

### PR DESCRIPTION
**Pull request by welwood08**
fixes #414 again

Hopefully this doesn't turn into whack-a-mole (ie if fosshub really doesn't want chocolatey doing its thing they come here and say so).

### CODE REVIEW

**Comment by welwood08** [comment]
Thinking again, is there a more generic way to do this that doesn't need all consumers of the fosshub helper to make modifications?

**Comment by AdmiringWorm** [comment]
unfortunately this is something I've been trying for some time now.
sometimes it works sometimes it doesn't.
Looks to be because fosshub sets such a short time before the links expires (around 4-5 seconds, could be faster)

**Comment by AdmiringWorm** [comment]
> Thinking again, is there a more generic way to do this that doesn't need all consumers of the fosshub helper to make modifications?

Not that I know of, except implementing a new function users can call to get the headers.

**Comment by welwood08** [comment]
Well if it would be something that required consumers of the fosshub extension to make changes it could surely just be a wrapper around `Install-ChocolateyPackage` that accepted the same parameters and performed the necessary preparation logic?

In other words, consumers would just call `Install-ChocolateyPackageFromFosshub`. That function could worry about finding the correct url/url64, setting the right headers, anything else fosshub might require in the future before calling `Install-ChocolateyPackage` itself.

**Comment by AdmiringWorm** [comment]
that is of course an option, I'm off to bed for the night now but I'll try looking into something like that tomorrow.

**Comment by majkinetor** [comment]
Outdated, see https://github.com/chocolatey/chocolatey-coreteampackages/pull/441

**Pull request closed without merging**
