### PR TITLE
(winpcap) Embedded package

### PR DESCRIPTION
**Pull request by jack1142**
## Description
This makes the package winpcap embedded. I added legal folder with verification file and license and edited update script, so it embeds the packages. Also I updated README with information needed by license.

## Motivation and Context
Package should be embedded if allowed and this app's license allows us to embed the installer (ref: #866)

## How Has this Been Tested?
I checked update.ps1, to see if it works properly, I tested the package in testing environment to see, if it installs and uninstalls properly.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
BTW, I see a little copy-paste from a different PR you submitted
> This makes the package tv-browser embedded.

should be winpcap, right?

**Comment by jack1142** [comment]
Yep, it should, I sent a few PRs and I basically do the same thing in all of those PRs anyway, sometimes there is something additional, but usually not, so the base is the same. I know that I won't miss something this way.
BTW, it's the first time I saw that you change this to "New feature", I'll know that I should check it in next PRs with embedded packages (as I will probably lead this issue to an end anyway)

**Comment by AdmiringWorm** [comment]
I've pretty much been changing to `New feature` for all of your PR's (since it wasn't a major deal, I didn't bother to mention it).
Since it isn't really a bug that the packages aren't embedded, so it feels rather as a new feature/enhancement.

**Comment by jack1142** [comment]
True, I just wasn't sure what to check as it's not exactly a feature, but more of an enhancement, so it didn't exactly fit, but probably it's still better than calling it bug fix.

**Comment by AdmiringWorm** [comment]
I'm actually surprised that I missed adding an 'enhancement' checkbox.
Oh well, note to myself to get around to do that then.

**Pull request merged**
