### PR TITLE
Bring in Tonigellida's packages

### PR DESCRIPTION
**Pull request by Redsandro**
I finished the puzzle of splitting @adgellida's jobs into individual package `xml` files.

__Phase 1__ complete.

__Phase 2__ is adding the `chocolatey` user for all these packages at once: https://github.com/chocolatey/chocolatey-coreteampackages/issues/32#issuecomment-69495752

__Phase 3__ is checking all the packages. Volunteers?

---

https://github.com/chocolatey/chocolatey-coreteampackages/issues/32

### CODE REVIEW

**Comment by Redsandro** [comment]
Note that this branch is on `chocolatey` so you can all fetch and commit to it.

**Comment by TomOne** [comment]
@Redsandro, keep in mind that in the meantime many of adgellida’s packages were handed over to other maintainers.

Some of them followed the [maintainer handover process](https://github.com/chocolatey/chocolatey/wiki/PackageMantainerHandover) and created a pull request to remove them from his repo, e.g. https://github.com/adgellida/chocolateyautomaticpackages/pull/9, but others did not.

We need to find out which packages were handed over and remove them from this PR before it can be merged.

To be honest, I’m not a big fan of bringing in a large number of packages that were previously not maintained by a core team member. The fact that many maintainers have taken over maintainership of adgellida’s packages shows that the Chocolatey community is quite vital. In that way, external maintainers have the chance to maintain packages of software which they are really interested in. I think it is more motivation for the community if folks can take over maintainership rather than taking away this chance by moving them all to the core team repo. You don’t have to agree with this, it’s just my humble opinion. :smile_cat:

**Comment by Redsandro** [comment]
The issue was open, so I thought I begin by making all packages available.

Everyone can feel free to delete the packages that are known to be maintained by others. For unmaintained ones, you can now merge the single package from this branch including the (if I did it correctly) ketarin `xml` adapted to the wishes of this repo.

Using some database trickery you can probably get a list of packages that were recently pushed by non-tonigellida maintainers and figure out which ones are no longer relevant this way, remove them, and push the removal back to this branch.

If what you are saying is that we should not take over a considerable amount of packages this way, I feel silly for having made this effort. But I guess it keeps me off the streets. :P

**Comment by TomOne** [comment]
> If what you are saying is that we should not take over a considerable amount of packages this way, I feel silly for having made this effort. But I guess it keeps me off the streets. :P

Yes, I should have expressed these thoughts before. For now I’m good with bringing in these packages. But we should discuss this matter for possible future packages.

Thanks for your efforts. :+1: 

> Phase 3 is checking all the packages. Volunteers?

Yes. I’m volunteering to check and improve **some** of these packages. Checking all of them is too much effort for me. :smiley: Perhaps we should set up a checklist in this issue where we see the state of this packages.

**Comment by gep13** [comment]
> Phase 2 is adding the chocolatey user for all these packages at once: #32 (comment)

I have all the emails that were sent out requesting the ```chocolatey``` user to be added as a maintainer, all that I would have to do is to click on the various links :-)  If another solution doesn't present itself, I am happy to start that process, if everyone is in agreement that we should do it.

**Comment by gep13** [comment]
> Yes. I’m volunteering to check and improve some of these packages. Checking all of them is too much effort for me. :smiley: Perhaps we should set up a checklist in this issue where we see the state of this packages.

@TomOne this really speaks to what I asked you about before, i.e. a step by step list of things to check for.  As probably one of the most experienced people at looking at packages and their contents, I think it would be great, if when going through a ```couple``` of these packages, you could create a list of things that you notice aren't quite right.  That way, we could start to have a checklist of thing to look for.

Yes, I appreciate that we have the guidelines and people if they are not familiar with them should read them, but I still think a checklist of things to look for, in some sort of an order, would greatly help with this effort.

In the case of looking at a ketarin file, I am thinking of things like:

* Make sure ExecuteCommand is not populated
* Make sure UserAgent is blank
* Make sure Category is empty

If we can get to a point where we have a manual checklist of things to look for, I think we could start scripting out some of these tasks, so that they become a very simple task that anyone can do.  This was really suggested by @Redsandro in another thread discussion.

What are your thoughts?

**Comment by gep13** [comment]
> To be honest, I’m not a big fan of bringing in a large number of packages that were previously not maintained by a core team member. The fact that many maintainers have taken over maintainership of adgellida’s packages shows that the Chocolatey community is quite vital. In that way, external maintainers have the chance to maintain packages of software which they are really interested in. I think it is more motivation for the community if folks can take over maintainership rather than taking away this chance by moving them all to the core team repo. You don’t have to agree with this, it’s just my humble opinion. :smile_cat:

I am not sure I 100% agree with the above.  Just because we bring a package into the core team packages repo, doesn't mean that a person can no longer maintain it.  Quite the opposite.  My vision of the core team packages repo is a central path to store both automated and manual Chocolatey Packages.  Just because we store the source code in one place, doesn't mean that someone who is **not** in the Core Team, can't maintain it.  They can continue to maintain it through pull requests.  The benefits to them is that they have someone else looking at the changes that they are making, and also a dedicated Ketarin instance which is checking for new versions of application every hour.

Does that make sense?

**Comment by Redsandro** [comment]
All makes sense to me. For the pull versus not pull, I agree with @gep13. At least we have the packages that have some fans in the core repo, but it doesn't mean that the packages are maintained by us. We just have control over the update process and don't have to trust that the original maintainer ketarin machine will stay up until a new maintainer presents itself.

@TomOne I appreciate you taking the task of checking _some_ packages. I suggest when you or anyone else takes it upon themselves to take in a few packages, they clone this branch, move the relevant packages to their own branch, and push the now 'deleted' files back onto this branch.

Similarly @gep13 can remove the packages that he determined to have new maintainers in the meantime, or suggest to those maintainers that they move their package to `core team packages` in stead, and/or suggest they make autopackages, linking to the ketarin `xml` settings that are available in this branch.

Also, just a thought, I think new maintainers are awesome, but if they want to maintain a package manually although the previous maintainer had made an autopackage, the package is better off staying an autopackage in the core repo as opposed to have a manual updating maintainer.

We should encourage maintainers to use the core repo and PR's for updates. Can we give maintainers who use the core repo for pushing a _"Core team contributor_" badge next to their name as a symbolic reward or something?

> @gep13 said:
I think we could start scripting out some of these tasks, so that they become a very simple task that anyone can do. This was really suggested by @Redsandro in another thread discussion.

For the `xml` part, if the relevant parts and unsettable or static parts are documented, we can automate this using `xslt`. A bit of a puzzle but pretty powerful. [Here's how it split the database into separate packages](https://github.com/chocolatey/chocolatey-coreteampackages/commit/a4899f37d6872244ed18280ae44f446f1acbec32).

**Comment by aronovgj** [comment]
just saw this. for what its worth, these are the packages i took over from toni. i didn't adopt his ketarin xml though and made my own ones. i couldn't maintain some of the more complex regex anyway:

CrystalDiskInfo
Malwarebytes Anti-Malware
HD Tune
CCEnhancer
CPU-Z
Aida64 Engineer (waiting to be added as a maintainer)


i'm a little confused after reading this... will you want those who took over the packages to create a pull request? keep updating it on their own? or are you still undecided?

**Comment by Redsandro** [comment]
Thank you @TomOne. :+1: 

My idea was that you create a PR that removes the packages that you took over. That way, the list of packages on this branch all still needs to be taken over.

Otherwise someone comes along, makes a lot of effort to port some packages, only to find out that someone else already did that.

**Comment by Redsandro** [comment]
Merged master in for now, just so branches are compatible.
Just __never__ merge this pull request.

I don't even know why this is a pull request. I will cancel this pull request.

This is just a library for packages that people might want to adopt from tonigellida. It's a lot of work. Just let it sit there.

**Comment by Redsandro** [comment]
Do __not__ delete branch.

**Comment by majkinetor** [comment]
I am about to delete branch since there is no activity for a year or so. I will leave this here for a day and if there are no comments the branch is out.

**Comment by gep13** [comment]
@Redsandro what are your thoughts around this?

**Comment by majkinetor** [comment]
I think we should create one wiki page with unmaintained repos and other folsk can then choose something from there if they want. 

Some packages are already here.

**Comment by Redsandro** [comment]
:+1:

**Pull request closed without merging**
