### PR TITLE
(vcredist140, vcredist2017) update to 14.10.25017.0

### PR DESCRIPTION
**Pull request by jberezanski**

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
ignore the failing appveyor build, bad logic in the test script (Need to look into that at some point)

**Comment by jberezanski** [comment]
> Have you uploaded it yourself to chocolatey?

No, I intended to use AU/AppVeyor. By the way, does the PUSH syntax support pushing multiple packages?

**Comment by AdmiringWorm** [comment]
@jberezanski yes it those.
For this one for instance we can just add `[PUSH vcredist140 vcredist2017]` in the merge header.

You can try it yourself if you want, or just let me know when you're ready for it to be merged.

**Comment by jberezanski** [comment]
Thanks, I'll try it.

**Pull request merged**
