### PR TITLE
(git-lfs) Migrate git-lfs packages

### PR DESCRIPTION
**Pull request by pascalberger**
This PR is to move the git-lfs packages from https://github.com/pascalberger/chocolatey-packages to the Core Team Packages.

I invited the Chocolatey user as a maintainer.

### CODE REVIEW

**Comment by majkinetor** [comment]
Would u embed it ?

**Comment by pascalberger** [comment]
@majkinetor Sorry don't understand what you mean. Could you please explain

**Comment by majkinetor** [comment]
Please see [1.1.4 - Embed a package if allowed](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#114-embed-a-package-if-allowed).

**Comment by pascalberger** [comment]
@majkinetor Do you mean the installer embedded in the git-lfs.install package or an additional package?

**Comment by majkinetor** [comment]
Installer embedded in the git-lfs.install package.

**Comment by pascalberger** [comment]
@majkinetor OK, I see the point of having an embedded package. I'll contact GitHub about getting the distribution rights. Is there a reason why this didn't came up for the Visual Studio Code or SourceTree package? Wouldn't it also make sense to make them embedded packages too?

**Comment by majkinetor** [comment]
>  I'll contact GitHub about getting the distribution rights. 

There is no need for that. Its MIT license, just include it. 

> Is there a reason why this didn't came up for the Visual Studio Code or SourceTree package? 

Yes, SourceTree doesn't allow redistribution. VSCode seems to be not redistributtalbe too. For those you would need to ask vendor.

**Comment by majkinetor** [comment]
To be honest it would be good to have VSCode embedded here, its probable that they will give redistribution rights for binaries (source code is license MIT AFAIK).

BTW, it VSCode currently fails updater on [force test](https://gist.github.com/gep13/b733b29e320a8c05bc99cc0bf59cd8d1#visualstudiocode) because it must import extension in updater. If it is embedded, this is no longer required.

**Comment by pascalberger** [comment]
@majkinetor I updated it to be an embedded package

**Comment by majkinetor** [comment]
Looks good.

Just set the nuspec version of virtual package to be the same as for install package. I will force update for both.

**Comment by pascalberger** [comment]
@majkinetor Updated the `git-lfs.nuspec`

**Comment by majkinetor** [comment]
Failed now https://gist.github.com/bd2eaa76f2a9ab739ca0544c502dca6e/91468e81cfffeccfbf018901fa089f013701a3e3

**Comment by pascalberger** [comment]
@majkinetor @gep13 You need to accept the invite as package moderator. I'll have a look at the other error.

**Comment by gep13** [comment]
Chocolatey user has been added to the package.

**Comment by pascalberger** [comment]
@majkinetor Any idea what the problem with the git-lfs is in the force tests? As it seems to work actually since they were updated and also works for me locally.

**Comment by majkinetor** [comment]
Definitelly network related, should be ignorred. Both packages are now pusshed.

**Pull request merged**
