### PR TITLE
(vscode-icons) Update according to the guidelines

### PR DESCRIPTION
**Pull request by pascalberger**

### CODE REVIEW

**Comment by pascalberger** [comment]
@gep13 Do you want to push this? Otherwise you can remove the `Push required` label

**Comment by gep13** [comment]
@pascalberger @AdmiringWorm sorry, I have been out of the loop on this repo, still playing catch up with a few things.  I thought there was now functionality to push individual packages based on a commit message.

**Comment by pascalberger** [comment]
Yes this works, but don't know if it works also with manual packages & package fix notation? @AdmiringWorm

**Comment by gep13** [comment]
@pascalberger let's give it a try 😄

**Comment by AdmiringWorm** [comment]
@gep13 , @pascalberger 
I'm sorry, I never noticed it was a manual package.
Yeah, the functionality to push package have been present for quite some time I belive.
Just add `[PUSH packageName]` to the commit title.

**Comment by AdmiringWorm** [comment]
Just a note on that though, it won't use package fix I believe.
It will just push the package as is.

**Comment by pascalberger** [comment]
@AdmiringWorm So for pushing manual packages with package fix notation we need to update the version in the source first and then push it with the commit title syntax?

**Comment by AdmiringWorm** [comment]
@pascalberger 
Yeah, I believe so.

**Comment by pascalberger** [comment]
Pushed with https://github.com/chocolatey/chocolatey-coreteampackages/commit/79c4fb81c60a7f9b05f9e241831ec3a896c7b900

**Comment by gep13** [comment]
>@pascalberger said...
So for pushing manual packages with package fix notation we need to update the version in the source first and then push it with the commit title syntax?

>@AdmiringWorm said...
Yeah, I believe so.

And I think that this makes sense.  Since it is just a push, there is no updating of files in the repository, so source files should be made to be the required end result, prior to pushing.

**Pull request merged**
