### PR TITLE
(virtualdub) fixes 404 + general improvements

### PR DESCRIPTION
**Pull request by Link-Satonaka**
Sorry, I'm still not familiar with AU. Whomever writes the update.ps1
should please search/replace {{Build}} from chocolateyinstall.ps1, to
match the build number on sourceforge

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
I'm sorry to say, but without this also being migrated to AU it is unlikely that this PR will be merged.
Unless someone else steps up to create the necessary logic to update it with AU.

**Comment by Link-Satonaka** [comment]
I was reading up on AU a few hours ago, I'll give it a shot later today.

**Comment by AdmiringWorm** [comment]
@Link-Satonaka 👍 
Please don't hesitate to ask on our gitter channel if you have any questions:
https://github.com/chocolatey/chocolatey-coreteampackages

or in the official AU channel of course
https://gitter.im/chocolatey_au/Lobby

**Comment by AdmiringWorm** [comment]
@Link-Satonaka I had a look at the website of this package,
and since it seems there hasn't been any development for it since 2013, this package don't need to be migrated to AU.
Rather it should just be updated according to our [Contribution Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md) and embedded (as well as creating a simple update.ps1 in the package root directory to just download the files, since we don't check in binaries).
The moved to the manual directory.

If you could do those things, that would be great.

**Comment by Link-Satonaka** [comment]
ugh, git is complicated. I'll just close this and start over.

**Pull request closed without merging**
