### PR TITLE
(foshub.extension) Fixed fosshub parsing to find the download url in any attribute [PUSH chocolatey-fosshub.extension]

### LINKED ISSUE #414: (fosshub.extension) Download URL within "xdts"-attribute
The package does no longer work for me because the download url of the binaries is stored within the xdts-attribute of the link now instead of the data-attribute.

https://github.com/chocolatey/chocolatey-coreteampackages/blob/e17820954cdce01bf1979a4ecaa7b7baa0612706/extensions/chocolatey-fosshub.extension/extensions/Get-UrlFromFosshub.psm1#L33

### PR DESCRIPTION
**Pull request by welwood08**
fixes #414

While debugging I noticed the referrer was being sent as a literal string - changed quotes.
Tested working with an update of my local audacity install on Win8.1.
I should say I'm not too familiar with PowerShell syntax, so please let me know if there's anything in the regex that might break it (in older PS versions etc).

### CODE REVIEW

**Comment by majkinetor** [comment]
Checked qbittorrent and it installed OK:

```
## welwood08-fosshub~> Test-Package -Vagrant $null

Package info
  Path:         C:\work\_chocolatey\chocolatey-coreteampackages\automatic\qbittorrent\qbittorrent.3.3.7.20161130.nupkg
  Name:         qbittorrent
  Version:      3.3.7.20161130

Testing package install
Installing the following packages:
qbittorrent
By installing you accept licenses for the packages.

qbittorrent v3.3.7.20161130 (forced)
qbittorrent package files install completed. Performing other installation steps.
Using system proxy server '10.35.9.55:8080'.

Download of abdi14bq.zhn (-1 B) completed.
Using system proxy server '10.35.9.55:8080'.
Downloading qBittorrent 32 bit
  from 'https://download.fosshub.com/Protected/expiretime=1480586451;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9xQml0dG9ycmVudC5odG1s/2e637ce502756f049095e82a108d0a2903922e68f934c14a524b4c3177d2b4f6/qBittorrent/qbittorrent_3.3.7_setup.exe'
Using system proxy server '10.35.9.55:8080'.

Progress: 100% - Completed download of C:\Users\majkinetor\AppData\Local\Temp\chocolatey\qbittorrent\3.3.7.20161130\qbittorrent_3.3.7_setup.exe (15.7 MB).
Download of qbittorrent_3.3.7_setup.exe (15.7 MB) completed.
Hashes match.
Installing qBittorrent...
WARNING: Exit code '1223' was considered valid by script, but not as a Chocolatey success code. Returning '0'.
qBittorrent has been installed.
 The install of qbittorrent was successful.
  Software installed as 'exe', install location is likely default.
```

However, update.ps1 does make a problem:

```
## welwood08-fosshub~> .\update.ps1
WARNING: The names of some imported commands from the module 'extensions' include unapproved verbs that might make them less discoverable. To find the commands with
unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
qbittorrent - checking updates using AU version 2016.11.26.112846
nuspec version: 3.3.7.20161130
remote version: 3.3.7
No new version found, but update is forced
New version is available
Automatic checksum started
Using system proxy server '10.35.9.55:8080'.

Download of 5t31goqp.ybp (-1 B) completed.
Attempt to use original download file name failed for 'qBittorrent.html'.
Copying qBittorrent
  from 'qBittorrent.html'
Copy-Item : Cannot find path 'C:\work\_chocolatey\chocolatey-coreteampackages\automatic\qbittorrent\qBittorrent.html' because it does not exist.
At C:\Users\majkinetor\AppData\Local\Temp\chocolatey\au\chocolatey\helpers\functions\Get-ChocolateyWebFile.ps1:350 char:5
+     Copy-Item $url -Destination $fileFullPath -Force
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\work\_chocol...Bittorrent.html:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Chocolatey expected a file to be downloaded to 'C:\Users\MAJKIN~1\AppData\Local\Temp\chocolatey\qbittorrent\3.3.7.20161201\qBittorrentInstall.exe' but nothing exists at  that location.
At C:\Users\majkinetor\AppData\Local\Temp\chocolatey\au\chocolatey\helpers\functions\Get-ChocolateyWebFile.ps1:358 char:24
+ ... .Exists)) { throw "Chocolatey expected a file to be downloaded to `'$ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Chocolatey expe... that location.:String) [], RuntimeException
    + FullyQualifiedErrorId : Chocolatey expected a file to be downloaded to 'C:\Users\MAJKIN~1\AppData\Local\Temp\chocolatey\qbittorrent\3.3.7.20161201\qBittorrentIns
   tall.exe' but nothing exists at that location.
```

The same is true for other packages. 

Regex is OK.

**Comment by AdmiringWorm** [comment]
@majkinetor 

that's odd, I see get no errors on my end.
Neither when running update.ps1 or using the test_all.ps1

**Comment by majkinetor** [comment]
Can you delete your temp directory and try again ? AU monkey patches chocolatey once a day, if you installed foshub extension locally it still uses the previous one.

**Comment by AdmiringWorm** [comment]
@majkinetor in such a case, it would still use the old version of the extension on my computer as I only installed the new version of the extension on the VM not on my computer.

However, cleaned the temp directory any any cache directories I use for chocolatey.
Not getting any error messages at all.

**Comment by majkinetor** [comment]
OK, then this is ready to go I guess, it must be something local for me.

**Comment by AdmiringWorm** [comment]
I'll try one more thing first, setting up a brand new VM to test the update in.

**Comment by AdmiringWorm** [comment]
@majkinetor finally got the vm up and running, and tested the qbittorrent package and it still works there.
So I'm merging this now

**Comment by majkinetor** [comment]
Great, thx for testing it out.

**Comment by AdmiringWorm** [comment]
@majkinetor No problem, remind me to push out a fix for the affected packages when this one passes validation (just in case I forget)

**Comment by majkinetor** [comment]
You can't forget if you add a label :) I will add it here instead on each app.

**Comment by majkinetor** [comment]
Its approved.

**Comment by AdmiringWorm** [comment]
I know, I'm in the process to push the packages.
Little unsure about light alloy though, but @gep13 suggested to me yesterday to just change the 4th part to the fix notation since the program hasn't been updated since 2015

**Comment by majkinetor** [comment]
Yeah, just add 1 to revision.

**Pull request merged**
