### PR TITLE
(nuget.commandline) Determine latest version from nuget.org

### LINKED ISSUE #820: (nuget.commandline) Update failing
## Current Behavior
Update of nuget.commandline throws an error: https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e#nugetcommandline

### PR DESCRIPTION
**Pull request by pascalberger**
## Description
Determine latest version from nuget.org and add support for pre-release versions

## Motivation and Context
Fixes #820

## How Has this Been Tested?
Tested locally

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package have been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this mean usually the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this mean usually the notes in the description of a package).
- [x] All files is up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
@pascalberger the appveyor build fails for this PR:
https://ci.appveyor.com/project/chocolatey/chocolatey-coreteampackages/build/2292-xdjqfojf#L147
(ignore the error message further down, it's from the test script itself which is unrelated to the failure of updating this package).

**Comment by pascalberger** [comment]
@AdmiringWorm Any idea what the `Invalid job state for nuget.commandline:  Blocked` means? I assume its caused by the `Find-Packages` call [here](https://github.com/chocolatey/chocolatey-coreteampackages/pull/822/files#diff-25fdf79c9a692cdfad0afe85cbcb1e9fR31)

**Comment by AdmiringWorm** [comment]
@pascalberger Unfortunately I have no idea, the au_temp log is empty so no information there.
But my guess would be due to the `Find-Package` as well (maybe it's not available on the server?)

**Comment by pascalberger** [comment]
@AdmiringWorm Any idea whats causing [this](https://ci.appveyor.com/project/chocolatey/chocolatey-coreteampackages/build/2297-etlqywqs#L165)?

Can it be a problem in `Test-RepoPackage.ps1` with eg. two `-` in the version?

**Comment by AdmiringWorm** [comment]
@pascalberger most likely a problem with the regex used to get the version of the nupkg package.

I'm about to head for bed, but I'll try to get a chance to look at it tomorrow.

**Comment by pascalberger** [comment]
@AdmiringWorm [This](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/scripts/Test-RepoPackage.ps1#L375-L377) seems wrong to me for a file with name `nuget.commandline.4.3.0-preview3-4168.nupkg`

**Comment by AdmiringWorm** [comment]
> Can it be a problem in Test-RepoPackage.ps1 with eg. two - in the version?

yeah, most likely.
Unfortunately it seems I won't have any time to look into it today either, but anyhow. Since this PR doesn't touch upon the install/uninstall script at all, we'll ignore the failure and merge this PR.

**Pull request merged**
