### PR TITLE
(blender) Migrated to AU

### PR DESCRIPTION
**Pull request by AdmiringWorm**
* Added update.ps1
* Updated chocolateyInstall.ps1
* Updated chocolateyUninstall.ps1 to use 'chocolatey-uninstall.extension'
* Updated license url
* Added project source url
* Added bug tracker url
* Added mailing list url
* Updated release notes url
* Added chocolatey-uninstall.extension dependency

**NOTE:** latest version (2.78) is in moderation, and needs to be updated.

### CODE REVIEW

**Comment by majkinetor** [comment]
@gep13 

I vote that we move all those different extensions that are used the most to core. This one is perfect example.

**Comment by majkinetor** [comment]
Can you recheck, this doesn't look OK


```
C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\blender\2.78\blender-2.78a-windows32.msi is of content type text/plain; charset=UTF-8
C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\blender\2.78\blender-2.78a-windows64.msi is of content type text/plain; charset=UTF-8
   blender is updated to 2.78 and pushed
```

**Comment by AdmiringWorm** [comment]
@majkinetor I believe this is just because the server returned an incorrect content type.
I tried to find a workaround for it, but couldn't. It still installs correctly and runs as it should.
I've seen these warnings before on other packages, which also installed correctly.

**Comment by majkinetor** [comment]
OK, thx. Just put a note on it next time so that I don't trip out.

**Comment by AdmiringWorm** [comment]
```
C:\WINDOWS\system32> cinst blender --version 2.78 -y
Chocolatey v0.10.3
Installing the following packages:
blender
By installing you accept licenses for the packages.

blender v2.78
blender package files install completed. Performing other installation s
Downloading blender 64 bit
  from 'http://ftp.nluug.nl/pub/graphics/blender/release/Blender2.78/ble
WARNING: D:\Cache\Chocolatey\blender\2.78\blender-2.78a-windows64.msi is
Progress: 100% - Completed download of D:\Cache\Chocolatey\blender\2.78\
Download of blender-2.78a-windows64.msi (84.01 MB) completed.
Hashes match.
Installing blender...
blender has been installed.
 The install of blender was successful.
  Software installed to 'C:\Program Files\Blender Foundation\Blender\'
```
image

**Comment by AdmiringWorm** [comment]
@majkinetor ok, I'll remember to that the next time.

**Comment by majkinetor** [comment]
Heh, manual cinst you should really try new `Test-Package` with my fork of chocolatey-test-environment if you want to be xtra efficient.

**Comment by AdmiringWorm** [comment]
@majkinetor doesn't that only work with local nupkg files?
I had already removed the nupkg file, so it was easier to just use cinst this time.

**Comment by majkinetor** [comment]
No it doesn't, it now works with everything, it works with install, uninstall, parameters, everything you might need. And its way faster, I changed a lot of things.

**Pull request merged**
