### PR TITLE
updated smartftp icon

### PR DESCRIPTION
**Pull request by matbech**

### CODE REVIEW

**Comment by gep13** [comment]
@matbech is there a reason for making the SmartFtp Icon smaller?

**Comment by matbech** [comment]
Nope this wasn't my intention. I have incorrectly assumed that the size will be set in the img element on the package page. But this is not the case. I have changed the default size to 128x128 now (same as current size).

**Comment by gep13** [comment]
Perfect, thank you! :+1:

**Comment by matbech** [comment]
Thank you.

**Pull request merged**
