### PR TITLE
Added CutePDF and DJV

### PR DESCRIPTION
**Pull request by Redsandro**
I had a fight with `git` so I hope this is okay

### CODE REVIEW

**Comment by gep13** [comment]
@Redsandro are you in a position to fix up this pull request so that we can get it pulled in?  Thanks!

**Comment by gep13** [comment]
@Redsandro did you see my comment above?

**Comment by Redsandro** [comment]
Sorry I did not see this. I would be happy to fix the relevant things at some point but I'm afraid I have used up my chocolatey hours on other packages. Just leave this here, I'll get around to fixing them at some point!

---

Note that those trivial things like spaces, lines and vars, I don't really care about them. _(I have $pwd in my templates because the Microsoft way of getting the working dir is unintuitive bs, and I like having it there if some update requires me to know the pwd because otherwise I have to search for the bs way to do it.)_  
I think it requires a caring individual less time to fix it themselves than to write an elaborate post about them.

As for ketarin, I keep making the same 'mistakes' because my ketaring vm setup. Is there a trick to export only the relevant settings? (So I don't have to manually edit the xml to remove stuff.) Perhaps you have documented exactly how chocolatey's ketarin settings are set up, so I can imitate that for my own vm so that moving a package to core repo is easier? 

For example, it's easiest to only have to make edits in one place. That's why I have the packageId there so that I don't have to edit the execution settings.

Additionally, the things about the path and not having a category and not having batch code for chokopkgup and all other relevant comments should be written [in the wiki](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#automatic-packages), not as an after thought after committing to the best of ones knowledge.

Try to make the instructions so that there is no room for having to take educated guesses. If one has a 5 minute timeframe in their break to create a package they really think should be on chocolatey, they will commit once and then go on with their workday, with little motivation to fix things afterwards that weren't clear in the instructions. I sound harsher than I actually am, but this applies to some of the correspondence I read in package moderation as well: https://github.com/chocolatey/chocolatey.org/issues/150

**Comment by gep13** [comment]
> Perhaps you have documented exactly how chocolatey's ketarin settings are set up, so I can imitate that for my own vm so that moving a package to core repo is easier?

I will get this documented, I believe it is the best way to go, going forward

**Comment by Redsandro** [comment]
Girlfriend and I broke up so I guess I have time for this now...

**Comment by Redsandro** [comment]
Fuck, seriously, why do files I don't even touch get pushed? I didn't even stage them.

**Comment by Redsandro** [comment]
Clean PR here: https://github.com/chocolatey/chocolatey-coreteampackages/pull/45

**Comment by gep13** [comment]
> Girlfriend and I broke up so I guess I have time for this now...

Dude, sorry to hear that :crying_cat_face:

**Comment by gep13** [comment]
> Fuck, seriously, why do files I don't even touch get pushed? I didn't even stage them.

Are you running on a linux machine, or a windows machine?  What application are you using to edit the files?

I recently changed my git config settings based on some advice from @ferventcoder:

https://github.com/gep13/ChocolateyPackages/blob/master/gep13.gitConfig/tools/ChocolateyInstall.ps1

With the most important being this:

https://github.com/gep13/ChocolateyPackages/blob/master/gep13.gitConfig/tools/ChocolateyInstall.ps1#L25

I "thought" I had done all I needed to do in the .gitattributes file to make this work for everyone, but perhaps not :sad:

Was this a fresh clone of the repo?  Perhaps try re-creating a new clone and working off of that, after updating your git settings if they are not the same as what I linked to.  Definitely looks like a line feed issue.

**Comment by Redsandro** [comment]
> sorry to hear

Thanks. Best 13 months in recent history. I guess now it's time to build stuff with my hands, fight people, do dishes once a week and permanently put all my electric equipment on the dinner table. It will make me feel better.

> Are you running on a linux machine, or a windows machine? What application are you using to edit the files?

I am on many different computers, usually Linux Mint or Ubuntu or Debian. That's why I (almost) always do a fresh clone in `/tmp`. I like working in `/tmp` because I always set it up as `tempfs` (AKA memdrive that is clean after reboot)

Nano and [geany](http://www.geany.org/) are my favorite editors.

But this PR was originally cloned from when the repo had a different config. Applying the changes to a clone from `master` solved the issues. :)

**Comment by gep13** [comment]
> I guess now it's time to build stuff with my hands, fight people, do dishes once a week and permanently put all my electric equipment on the dinner table. It will make me feel better.

Fingers crossed! 

> But this PR was originally cloned from when the repo had a different config. Applying the changes to a clone from master solved the issues. :)

Sweet, glad we got that sorted! :smile_cat:

**Pull request closed without merging**
