### PR TITLE
(lockhunter) Updated to 3.4.3

### PR DESCRIPTION
**Pull request by sammynilla**
## Description
Updated LockHunter to 3.4.3 

## Motivation and Context
LockHunter had a minor update from 3.4.2 to 3.4.3.

## How Has this Been Tested?
Only two files were changed and the installation file was tested similarly to #1701. The checksum is the same as the downloaded executable directly from the application website.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by pauby** [comment]
@sammynilla awesome work! Thanks for your contribution!

**Comment by sammynilla** [comment]
Happy to be able to help! Although, I do happen to have a question in case you feel like you'd be able to answer it for me @pauby. I was curious if there were any other follow up processes required to have the package pushed to chocolatey for download? I noticed that before this PR there was also one to update the package to version 3.4.2, but the chocolatey package seems stuck at 3.3.4.

**Comment by pauby** [comment]
That was my bad @sammynilla. I used the wrong notation to push the package (curved instead of square bracket). It's been [pushed now](https://community.chocolatey.org/packages/lockhunter/3.4.3.146).

**Comment by sammynilla** [comment]
Thank you so much!

**Pull request merged**
