### PR TITLE
(vscode-csharpextensions) Update according to the guidelines

### PR DESCRIPTION
**Pull request by pascalberger**
Update metadata according to the guidelines

### CODE REVIEW

**Comment by pascalberger** [comment]
@gep13 Do you want to push this? Otherwise you can remove the Push required label

**Comment by gep13** [comment]
@pascalberger @AdmiringWorm sorry, I have been out of the loop on this repo, still playing catch up with a few things.  I thought there was now functionality to push individual packages based on a commit message.

**Comment by pascalberger** [comment]
Pushed with https://github.com/chocolatey/chocolatey-coreteampackages/commit/c9fa6ecb9194714b85bee670fceb7c3e9841f255

**Comment by AdmiringWorm** [comment]
@pascalberger fyi, you could have pushed this one at the same time as vscode-icons.
just put a space between the package names, the same goes for when you use [AU].
Wildcards also works.

**Pull request merged**
