### PR TITLE
FlashPlayerActiveX AU Update Two

### PR DESCRIPTION
**Pull request by RedBaron2**
Added the switch `-UseBasicParsing` to the IWR for fixing the "Vector Smash" Error
@AdmiringWorm 
This I hope fixes this package

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
Unfortunately, this will not work as it currently is.
The grabbing of the version also needs to be updated when using `-UseBasicParsing`.
When it is used, then `.ParsedHtml` and `.InnerText` isn't available.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
I will work on this, but could you tell me how many packages are processed before this package?
I will work on a update to the entire package like the old school days of ketarin

**Comment by AdmiringWorm** [comment]
There is no fixed order of the package updates.
All packages are updated in batches of 10, and when one is done the next one is started in no particular order.

**Comment by RedBaron2** [comment]
Thanks for the info. I'll keep you informed as to my results. PR's for the flash will be coming soon.

**Comment by AdmiringWorm** [comment]
I'll look forward to it.

**Comment by RedBaron2** [comment]
Oh one more thing is it possible anymore to do multi commits as PR's?

**Comment by AdmiringWorm** [comment]
multi commits as PR?
Not entirely sure what you mean?
If you're talking about merging multiple PR's at once, then yeah it's possible.
But you'll have to let us know if several PR's needs to merged at the same time.

**Comment by RedBaron2** [comment]
No what is mean is like the nuspec file and the ps1 file for these flash packages. I edit one it creates a new branch just for that file. I can't choose to save to the same branch anymore.

**Comment by RedBaron2** [comment]
nvrmnd I figured out a way stay tuned

**Comment by majkinetor** [comment]
Without -UseBasicParsing you will have to reg ex into RawContent to find what you want.

**Comment by majkinetor** [comment]
Since your REG stuff and HTML.close didn't work (see https://github.com/chocolatey/chocolatey-coreteampackages/pull/625#issuecomment-287291866), you should revert those lines). I will keep this open for new to find a working solution.

**Comment by RedBaron2** [comment]
@AdmiringWorm @majkinetor 
I found what could be a solution. It involves changing the url to have `?{packagename ending}` (ex: ?activex)
I came to this conclusion after seeing, and checking on my own the probable reasons for these packages to be 'vector smash ?' as AU puts it. All the url(s) for these updates are the exact same, and unless someone wants to take on the project of merging them into one update.ps1 file. The problem is local caching of the invoke-webrequest call. It in simple terms gets the file and then caches it. This cache is then used for the next call to the same url, and so on to the next package. This appears to be a caching issue of the url with power shell on Appveyor. The commit has been changed to address this caching issue. If it works the same can be fixed on the other flash packages.

**Comment by AdmiringWorm** [comment]
@RedBaron2 LGTM, I'm not completely sure it will work though.
But if you can rebase this PR towards the latest master (and fix any issues), we can merge it try it out.

**Comment by majkinetor** [comment]
Also, remove  `$HTML.close` as it is not needed.

> The problem is local caching of the invoke-webrequest call. It in simple terms gets the file and then caches it. 

I never experienced this and I doubt iwr cashes anything, maybe something upstream does that tho. You will have to provide evidence any way.

> All the url(s) for these updates are the exact same, and unless someone wants to take on the project of merging them into one update.ps1 file

If all 3 packages, if I understand you right, have almost the same update.ps1, AU allows them to share it.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
fixed the conflicts

@majkinetor 
> ...  provide evidence any way.

I will work on providing evidence.

> ... AU allows them to share it.

You mind sharing. I might have missed that section 😄

**Comment by majkinetor** [comment]
@RedBaron2 

See this part in docs: https://github.com/majkinetor/au#reusing-the-au-updater-with-metapackages

It is provided for metapackages but can be used in whatever manner. There are several examples on this repo, for example notepadplusplus.

**Comment by RedBaron2** [comment]
@AdmiringWorm @majkinetor 
If this fixes the issue of the AU error '... Vector Smash ?'. 
The community is getting anxious for the update to this/these package(s). The community is my main priority 😄

@majkinetor 
I will look into using AU's multi update.ps1 to make this easier in the future.

**Comment by RedBaron2** [comment]
@AdmiringWorm @majkinetor @gep13 
I did my own testing with Appveyor and these are the results. [Flash_Packages](https://ci.appveyor.com/project/RBZ/development)
I used the same [original code](https://github.com/RedBaron2/development/tree/master/automatic)
I don't know what is going on in the Chocolatey Appveyor environment to be causing the 'Vector Smash ?' error.
I can only ask for more details from the code, but that would have to come from @majkinetor 
`$pkg.Error = 'Job returned no object, Vector smash ?'`
This `error message` just doesn't give enough information to try and narrow this down.

If this is any help to anyone. You are welcome, and I will check back next week.
Enjoy the Weekend everyone. 😃

**Comment by majkinetor** [comment]
@RedBaron2 , executing packages 1 by 1 doesn't produce the problem, only when those are run trough updateall, so your above test is invalid.

**Comment by gep13** [comment]
@majkinetor are you aware of a solution to the problem being faced by @RedBaron2 and the flash packages? If so, are you in a position to provide a PR to solve the problem so that everyone can learn from it? Thanks!

**Comment by majkinetor** [comment]
@gep13 , no , I didn't find any solution for #382.

**Comment by majkinetor** [comment]
Actually, the solution is there. Just don't use `Invoke-WebRequest` but something else like `WebClient` or `curl` or `wget` or whatever else.

So @RedBaron2 , you should probably do that.

**Comment by AdmiringWorm** [comment]
closing this in favor of using the XmlDocument in #639

**Pull request closed without merging**
