### PR TITLE
SmartFTP: updated iconUrl

### PR DESCRIPTION
**Pull request by matbech**

### CODE REVIEW

**Comment by gep13** [comment]
I think the URL that you are after is this one:

https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/97d1e867fd5feaee1b89b24ffe6d40c22c819dc3/icons/smartftp.svg

**Comment by matbech** [comment]
Wouldn't it be better to use the url pointing to the master branch so that we don't have to update the iconUrl again when the icon is updated?

**Comment by gep13** [comment]
Unfortunately not, no.  There is an issue with package icons getting cached against the original URL (part of the way the CDN works), so when you change the icon, it won't get served up if you use the same URL.  You can find the details here:

https://github.com/chocolatey/choco/wiki/CreatePackages#package-icon-guidelines

**Comment by matbech** [comment]
Ah I understand. Thanks. I have updated the IconUrl accordingly.

**Comment by gep13** [comment]
Perfect! :+1:

**Pull request merged**
