### PR TITLE
kb2999226: fixed a few scenarios, simplified code

### PR DESCRIPTION
**Pull request by jberezanski**
Fixed installation on:
- Vista/2008 SP2
- Evaluation editions (e.g. "Microsoft Windows Server 2012 R2 Datacenter Evaluation") and, possibly, other less-known named editions

New feature: detecting lack of the requisite Service Pack on Vista/2008/7/2008 R2 (and suggesting the Chocolatey package for 7/2008 R2 SP1)

Code cleanup:
- simplified control flow
- fixed indentation

### CODE REVIEW

**Comment by jberezanski** [comment]
Thanks for merging! Could you please pack and push it to .org? Or is there some machinery in place that can/will do this?

**Comment by majkinetor** [comment]
The machinery exists for AU packages, not for manual packages.

**Comment by gep13** [comment]
@majkinetor I was going to reply with the same as you did.

Could AU include the ability to simply push a manual package, in the same way we do with commit messages?

**Comment by majkinetor** [comment]
This can be done in appveyor using AUs `Push-Package` in only few lines.

**Comment by majkinetor** [comment]
But without any reporting ofc.

**Comment by gep13** [comment]
@majkinetor understood.

**Comment by majkinetor** [comment]
@gep13 , @ferventcoder 

I implemented new command `[PUSH pkg1 ... pkgN]` that does this. See documentation on [AU wiki](https://github.com/majkinetor/au/wiki/AppVeyor#pushing-specific-automatic-or-manual-packages)

Check out [example build](https://ci.appveyor.com/project/majkinetor/au-packages/build/96) of my repository.

You can use this as of this moment on this repository.

**Comment by gep13** [comment]
@majkinetor VERY COOL! 👍

**Comment by gep13** [comment]
@jberezanski @majkinetor noice!

https://ci.appveyor.com/project/chocolatey/chocolatey-coreteampackages/build/293

**Comment by gep13** [comment]
Which resulted in this:

https://chocolatey.org/packages/KB2999226/1.0.20161030

Great work @majkinetor !!!

**Comment by jberezanski** [comment]
That is truly awesome! 😄

**Comment by ferventcoder** [comment]
Doh - I just noticed that the email address we tell folks for spam is not the one it uses now. O_o.

**Comment by ferventcoder** [comment]
On the other hand, super awesome add!

**Comment by gep13** [comment]
>@ferventcoder said...
Doh - I just noticed that the email address we tell folks for spam is not the one it uses now. O_o.

It might just be because it is early here, but I have no idea what this means 😄

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/commit/1ac1f63136243b65956a81d351d05967084cac7f

**Pull request merged**
