### PR TITLE
Modernized autohotkey.portable's ketarin xml

### PR DESCRIPTION
**Pull request by Elderry**
Rebased version.

### CODE REVIEW

**Comment by ferventcoder** [comment]
The contribution is appreciated and the changes in the ketarin script are still needed. I'm going to push fixes for the install script itself that I prefer it keep. Please rebase once those are in.

**Comment by ferventcoder** [comment]
Just pushed, please rebase.

**Comment by ferventcoder** [comment]
Also, check with @gep13 - he may have fixed up some of the ketarin scrips already.

**Comment by gep13** [comment]
@Elderry @ferventcoder thank you for taking the time to do this.  @majkinetor is in the process of switching all the autohotkey packages to use AU, as a result, I don't think we are going to need this PR.  I very much appreciate you taking the time to do it though.

**Comment by Elderry** [comment]
@gep13 , so can I get the result that AU is regarded as a better approach than chocopkgup + ketarin? Are you going to switch all packages to use AU?

**Comment by gep13** [comment]
@Elderry AU offers a number of benefits over Ketarin, no least the visualisation of the output of an AU run to see what did, and didn't happen.  Over time, we will be converting all packages in this repo to use AU, yes.  Any help that you can offer in this process would be gratefully accepted.

Myself and @majkinetor have already started converting some of the packages.

**Pull request closed without merging**
