### PR TITLE
(Julia) Migrated Julia

### PR DESCRIPTION
**Pull request by drelatgithub**
## Description
Julia is a promising high-level, high-performance programming language for technical computing. It is used by a large and increasing number of people, and recently it has entered the 1st major version, and is becoming more stable. This is to migrate the original Julia chocolatey package to core team packages.

## Motivation and Context

It fits the criteria of core team packages and automatic updating is needed for this package, hence the migration.

## How Has this Been Tested?
The install/uninstall/shimming have been tested on my local windows 10 machine, as well as the chocolatey test environment.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](https://github.com/FlorianRappl/Chocolatey-Julia)
- [Open Issues](https://github.com/FlorianRappl/Chocolatey-Julia/issues) *Add the different issues underneath, and tick those that are fixed in this PR*
  - [x] https://github.com/FlorianRappl/Chocolatey-Julia/issues/1
  - [x] https://github.com/FlorianRappl/Chocolatey-Julia/issues/5
- [ ] The original repository will be deleted or archived altogether if this PR is approved, since it is a one-package repository. (*Include the link to the opened PR that removes the package from the original location*)
- [x] The [migration guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Package-migration-process) have been followed, except for the PR to delete the original package (will do if required).

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
There is one problem though, your username does not match to any known usernames of the maintainer of this package.

I also can not see any history of any triage for this package either.
Before we can merge and proceed with the migration of this package, we either need approval from @FlorianRappl (which seem to be the actual maintainer), or you'll need to follow the package triage process first and be added as a co-maintainer ([see the documentation](https://chocolatey.org/docs/package-triage-process#the-triage-process) for the triage process).

**Comment by FlorianRappl** [comment]
I hereby approve this PR!

**Comment by AdmiringWorm** [comment]
@FlorianRappl thank you for confirming.

@drelatgithub no worries, and yeah I noticed you added yourself as a maintainer in the nuspec file (this isn't used on chocolatey.org though).
One thing I missed initially though, is that the chocolatey user is supposed to be listed as the first maintainer in the nuspec file (as per our contribution guidelines). No matter though, I'll change that when I merge this in.

I've added chocolatey as a maintainer as well (we need to do that so we can push packages from this repo).
I would suggest that @drelatgithub to be added as a maintainer on the package page as well, if you @FlorianRappl agree with that?

**Comment by FlorianRappl** [comment]
Yes @AdmiringWorm I agree to that - @drelatgithub did a fabulous job here and I trust him 100% on this one (plus I was often lacking behind with the recent releases; so if anything comes up on Julia's side I am sure having more maintainers on the choco package is helpful). Thanks!

**Comment by AdmiringWorm** [comment]
@FlorianRappl awesome.

@drelatgithub just to confirm, is your chocolatey username `drel`?
I'll send out a request so you can get added as a co-maintainer of the package (or @FlorianRappl could do that as well, since he is already the maintainer of the package).

**Comment by AdmiringWorm** [comment]
@drelatgithub I've added you as a maintainer, you should have received an email from chocolatey where you need to confirm to be added as a maintainer.

**Comment by drelatgithub** [comment]
Thanks @AdmiringWorm !

I still have a question though. It seems that the updated package of Julia has been submitted and approved on chocolatey, but the package in this repository remains untouched by auto-updaters. Is it the normal behavior?

**Pull request merged**
