### PR TITLE
(opera) Parameters for disabling desktop and taskbar shortcuts

### PR DESCRIPTION
**Pull request by jack1142**
## Description
I added support for two Opera installer arguments - one stops creating desktop shortcut for Opera and the other stops pinning Opera to Windows taskbar.

## Motivation and Context
This change provides better expierence for users, because you can disallow installer from creating desktop shortcut for Opera or pinning it to taskbar, so user won't need to remove shortcut by himself each time.

## How Has this Been Tested?
I packed package with `choco pack` and tested the package with `choco install opera -s . --params "/NoDesktopShortcut /NoTaskbarShortcut"` and with `choco install opera -s .` (to see, if it didn't destroy standard installation) and just in case I also tested uninstalling it.

Tested on Windows 10, version 1803

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by jack1142** [comment]
Ah, and to add to this, in my opinion it shouldn't create desktop and taskbar shortcut defaultly, but I'm not sure, if you would agree to change it, so for now I left it as it is.

**Comment by jack1142** [comment]
And one more thing, I wanted to add date to version but Opera already uses 4 part segmentation in version number :/

**Comment by AdmiringWorm** [comment]
> Ah, and to add to this, in my opinion it shouldn't create desktop and taskbar shortcut defaultly, but I'm not sure, if you would agree to change it, so for now I left it as it is.

while personally I also don't like to have desktop shortcuts by default, we should honor the defaults of the installer.

> And one more thing, I wanted to add date to version but Opera already uses 4 part segmentation in version number :/

Yeah, adding a date wouldn't work here. While there are ways we could push it out, it's not yet been added to the package (and probably won't be yet either). So basically, these changes won't be available until the next version of Opera hits.

**Comment by jack1142** [comment]
> Yeah, adding a date wouldn't work here. While there are ways we could push it out, it's not yet been added to the package (and probably won't be yet either). So basically, these changes won't be available until the next version of Opera hits.

Yeah I thought we will need to wait for next version, just wanted to point that out 👍

There's still some time until next release of Opera, because last one was released just 4 days ago, so there's time for revision of this PR and if anything is wrong I can still change it.

I just want to add these parameters, because with auto upgrading packages I need to remove this pin every week or two and that's a little annoying.

**Comment by AdmiringWorm** [comment]
The changes so far looks good, but I need to test if they are POSHv2 compatible.
I'm a little unsure if it is, with the regard of line 7,8 and 19 in the install script.

If everything works as it should, then it would be ready to be merged in.

BTW, just a tip for the future. You don't need to update the `<description>` element in the nuspec file, it's enough to update the README (the description is automatically updated from the README.md file during update)

**Comment by AdmiringWorm** [comment]
@jack1142 thank you for your contribution

**Pull request merged**
