### PR TITLE
New package: patch-my-pc

### PR DESCRIPTION
**Pull request by Redsandro**
Created ketarin cleanup xsl and added patch-my-pc for testing
---

---

This package needed to be added, but I used it as a testing ground for the `xsl` for stripping committed ketarin `xml`s from undesired variables.

I forgot where the discussion was. Part of it was here: https://github.com/chocolatey/chocolatey-coreteampackages/pull/44#issuecomment-69515311

### CODE REVIEW

**Comment by Redsandro** [comment]
I am not sure what a platform-independent or windows way is of applying `xslt 2.0` to an `xml` file, so I realize the `.sh` shellscript isn't very usable in it's current linux form.

Preferably we need something cross-platform. (python?) Once we figure that out, we can replace the input files with command line arguments or however this is best implemented.

**Comment by Redsandro** [comment]
Same protocol: Please dear god @gep13 @TomOne @ferventcoder add `patch-my-pc.ketarin.xml` to the ketarin machine.

**Comment by gep13** [comment]
Okay, let's not do this piece meal... looks like you are going to be merging a few things.  Go ahead with all the merges, and then I will add all the xml files into the Ketarin machine, just send me a list of all the ones that you want added.

**Comment by Redsandro** [comment]
Sure thing. I never expected that you would do this so quick. The plan was to _"please dear god"_ a few PR's, sit in the corner, and wait.

**Comment by gep13** [comment]
>@Redsandro said...
The plan was to "please dear god" a few PR's, sit in the corner, and wait.

Ha ha, I am here to help, when I can, I just need some gentle prodding sometimes :smile_cat:

**Comment by Redsandro** [comment]
@gep13 would you be so kind and add these to the ketarin machine?

* `absolute-uninstaller.ketarin.xml`
* `partitionassistant.ketarin.xml`
* `partitionassistantlite.ketarin.xml`
* `patch-my-pc.ketarin.xml`
* `renamemaster.ketarin.xml`
* `reshack.ketarin.xml`
* `tixati.ketarin.xml`

Sorry about the delay. I kept switching to other work because Chocolatey is rrrrreeeaaalllll slow and keeps throwing errors on `cpush` or moderate.

image

**Comment by gep13** [comment]
Done.

Yes, I have seen this happen as well.  I think @ferventcoder is aware of the issue though.

**Comment by Redsandro** [comment]
Thank you. :+1: :smile: :wine_glass: 

I've cleaned up a bunch of PRs and branches. Tested the packages, cheated by removing myself as maintainer and approved the packages.

**Comment by gep13** [comment]
Thanks for all your hard work today! :-)

**Pull request merged**
