### PR TITLE
(fosshub) Updated depdendencies

### PR DESCRIPTION
**Pull request by gep13**
@majkinetor @AdmiringWorm we can pull this one in once the outstanding question about the core-extension has been answered.

### CODE REVIEW

**Comment by gep13** [comment]
@majkinetor @AdmiringWorm do you think we should force push all the packages in this PR so that they update with the latest dependencies?

**Comment by AdmiringWorm** [comment]
I think that should be possible.
Not sure though.

**Comment by AdmiringWorm** [comment]
but is it really necessary?
Sure the uninstall extension is deprecated, but it has a dependency on the core extension so no harm not updating them?

**Comment by gep13** [comment]
Oh, yeah, everything should just work, I am not worried about that side of things.

More, just whether it is worth pushing out an updated package fix with the most recent dependencies, or just wait for the natural order of things to sort things out.

**Comment by AdmiringWorm** [comment]
personally, I feel this is such a small change that it isn't wort pushing out a package fix.
But that may just be me.

**Comment by gep13** [comment]
>@AdmiringWorm said...
personally, I feel this is such a small change that it isn't wort pushing out a package fix.
But that may just be me.

Nope. that is my opinion as well.  Just wanted to make sure 😄

**Comment by majkinetor** [comment]
I agree, if the package doesn't require new version of extension lets keep it that way. I update pacakge dep only when bug fixing extensions.

**Pull request merged**
