### PR TITLE
New package: vcredist2015

### PR DESCRIPTION
**Pull request by matbech**
This adds Visual C++ Redistributable Packages for Visual Studio 2015 RC
Please publish the package after it has been added. Thanks.

### CODE REVIEW

**Comment by ferventcoder** [comment]
I noticed this is from your master branch. We usually recommend you create PRs from feature branches.

**Comment by matbech** [comment]
I will create a feature branch in the future.

**Comment by ferventcoder** [comment]
Thanks!

**Comment by ferventcoder** [comment]
@matbech any reason you want to have have the c++ redist package here and not maintain it in your own repo?

Also @TomOne @Redsandro - thoughts?

**Comment by matbech** [comment]
I believe vcredist packages are essential and should be maintained in a repo managed by the chocolately team.

**Comment by ferventcoder** [comment]
:+1:

**Comment by matbech** [comment]
So any chance this will be merged/added?

**Comment by Redsandro** [comment]
@matbech could you build and push the `vcredist2015` package? And add `chocolatey` as a maintainer?

**Comment by matbech** [comment]
a great way to encourage users to contribute is to ignore PRs for at least 6 months

**Comment by gep13** [comment]
@matbech I am should now be in a position to better look after PR's into this repository.  Would you like to re-submit these packages into this repository?

Please accept my apologies for the length of time it has taken to look at this!

**Comment by matbech** [comment]
Let's see if we can convince the current maintainer (pocki_c) of the vcredist2015 package (https://chocolatey.org/packages/vcredist2015) to create a PR. His package is more up-to-date than the one in this PR.

**Comment by gep13** [comment]
@matbech sounds like a plan to me.  Are you in a position to reach out to him?

**Comment by matbech** [comment]
Yep, he said the PR is coming soon :-)

**Comment by gep13** [comment]
Sweet! Thanks, and sorry again for earlier delay!

**Comment by pocki** [comment]
I created a new PR #94 with my actual version of the package vcredist2015

**Comment by gep13** [comment]
>@pocki said...
I created a new PR #94 with my actual version of the package vcredist2015

Thank you for this!  Just looking at it just now.

**Pull request closed without merging**
