### PR TITLE
(Repository) Adding PR and Issue templates

### PR DESCRIPTION
**Pull request by AdmiringWorm**
## Description
The following changes in this PR adds templates for when people are opening issues as well as pull requests, which hopefully will make our life easier.

## Motivation and Context

The motivation came from being tired of not having a template to follow, usually ending up with a empty description.

## How Has this Been Tested?
Not applicable

## Screenshot (if appropriate, usually isn't needed):
Not needed

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package have been migrated from another repository)
- [x] Other

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this mean usually the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this mean usually the notes in the description of a package).
- [x] All files is up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/.github/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [ ] The changes only affect a single package (not including meta package).

// cc @majkinetor @gep13 @ferventcoder

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
> The poblem with github checkboxes is that history isn't monitored.

While that is true, I personally see that as a lesser evil for now.

> I have a 'wall of text' feeling in 100% of cases with issue templates. As long as it isn't mandated I am fine with having it.

I do agree with that, but it should still be encouraged to be used.

> Will changing the location of contributing doc invalidate the link that is presented by github when you push PR / issue ?

As long as it's inside the .github folder it shouldn't, if I read the docs correctly.
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by ferventcoder** [comment]
Let's not move CONTRIBUTING down to a subfolder. There are many folks who look for tgis file at top level - I'm not going to guess to look in the .github folder and neither will they. They should have the opportunity to read over CONTRIBUTING loooong before they are at the point of issuing a PR, in some cases it is going to save folks rework and being upset about not having found that file early on before they made their commits.

**Comment by AdmiringWorm** [comment]
Good point, I just moved it to keep the root directory as free of clutter as possible.
I'll move it back.

**Comment by AdmiringWorm** [comment]
@ferventcoder does everything look good now?

**Comment by ferventcoder** [comment]
Yes

**Pull request merged**
