### PR TITLE
SOFTWARE DEPRECATED: becyicongrabber

### PR DESCRIPTION
**Pull request by AdmiringWorm**
Since becyicongrabber hasn't gotten any updates since 2007, I've moved it to the
manual directory.
Before I did that though I did the following changes:
* added update.ps1 (just in case development starts anew)
* added BeCyIconGrabber.exe.gui
* update icon url
* updated install script

**NOTE:** It would need one last force push to add the checksum though

### CODE REVIEW

**Comment by gep13** [comment]
Nice one! Thanks for doing this!

**Comment by majkinetor** [comment]
> added update.ps1 (just in case development starts anew)

IMO this is waste of time.

**Comment by AdmiringWorm** [comment]
@majkinetor, I had already created it before I decided to move it to manual

**Comment by majkinetor** [comment]
BTW, I opted to delete ketarin files when I move package. First of all, its in the repo history if ever needed and it probably will never be needed.

**Pull request merged**
