### PR TITLE
vcredist2015: Updated to VS2015 Update 1

### PR DESCRIPTION
**Pull request by matbech**
updated vcredist2015 with VS 2015 update 1

### CODE REVIEW

**Comment by gep13** [comment]
@matbech thanks for getting this updated!

Any chance you can squash those three commits into one?

Also, I think a commit message similar to:

`(vcredist2015) Updated to VS2015 Update 1`

Would help when reviewing the commit messages later.

**Comment by matbech** [comment]
@gep13 updated title as suggested but I see no point in merging the 3 commits.

**Comment by gep13** [comment]
>@matbech said...
updated title as suggested but I see no point in merging the 3 commits

why not?  All the work in getting the package updated to this latest version is contained within those three files.  Why should I have to look at three separate commits in order to understand the context of the change?

Also, you have updated the title of the Pull Request.  I was suggesting you change the commit message itself.

**Comment by matbech** [comment]
Well then don't and feel free to update the packages yourself.

**Comment by gep13** [comment]
>@matbech said...
Well then don't and feel free to update the packages yourself.

**Comment by TomOne** [comment]
Is this ready to merge?

**Comment by gep13** [comment]
@TomOne I have merged this PR via this commit: https://github.com/chocolatey/chocolatey-coreteampackages/commit/5a9ce2df4984da5b8ba0b7df2b0af10845b9b180

**Pull request closed without merging**
