### PR TITLE
Created hostsman autopackage

### PR DESCRIPTION
**Pull request by Redsandro**
I get the following when I try to test:

```
The packages folder 'C:\code\mine\chocolateyautomaticpackages\name' does not exist. Perhaps you meant to specify the name as something else or you want to override the packages folder path setting of 'C:\code\mine\chocolateyautomaticpackages'. See chocopkgup.exe /help for details.
```

Could someone give a hint?

### CODE REVIEW

**Comment by ferventcoder** [comment]
you updated choco package up

**Comment by ferventcoder** [comment]
The folder location from the config, does it exist?

**Comment by Redsandro** [comment]
Yes, I updated choco package up. The location `C:\code\mine\chocolateyautomaticpackages\name` does not exist, but I have not entered that path in any file. Just cloned a VM, installed choco package up and ketarin, added script:

```
chocopkgup /p {appname} /v {version} /u "{preupdate-url}" /u64 "{url64}" /pp "{file}" /disablepush
```

Is anyone with a working setup in a position to test if this works? Maybe it's just good to go.

**Comment by ferventcoder** [comment]
You do need to update the chocopkup config - "C:\code\mine\chocolateyautomaticpackages\" is the default location.

**Comment by ferventcoder** [comment]
As for `name`, I can only say it's possible that you have another ketarin item in jobs and it needs updated or removed.

**Comment by Redsandro** [comment]
@ferventcoder @gep13 so I can't seem to set up a working ketarin for some reason. I can't even build packages that are in master. I would appreciate one of you with a working setup just checkout this PR and see if it builds, so it can be merged.

Or actually, the people who are requesting the updated package would appreciate this. :smile: 

---

We could use a vagrant box to set up a testing environment. But it's hard to set up a Windows vagrant box. The modern.ie boxes don't allow automatic setup through ssh.

**Comment by ferventcoder** [comment]
Would it help to pull this in and see what happens since it seems environmental?

**Comment by ferventcoder** [comment]
@gep13 thoughts!

**Comment by Redsandro** [comment]
Could you checkout `hostsman` in your running setup and run the `ketarin.xml` file, but run the command with `/disablepush`?

If it works, we can just merge and add it to the main ketarin machine.

**Comment by gep13** [comment]
@Redsandro this worked fine when I pulled it onto the ketarin machine, so looks like it is all good :+1:

**Comment by Redsandro** [comment]
I'm glad. Thank you! :+1:

**Pull request merged**
