### PR TITLE
(codeblocks) Updated to embedd installer

### PR DESCRIPTION
**Pull request by AdmiringWorm**

### CODE REVIEW

**Comment by majkinetor** [comment]
U r missing import to core. OR we na ditch that mechanism and preinstall it on AV. It will not be the same as package can use unpublished stuff this way but that rarelly happens and that package can still manually import.

**Comment by AdmiringWorm** [comment]
Since this one doesn't use au to download the the file, a reference to core extension shouldn't be needed.

**Comment by majkinetor** [comment]
Oh, yes, forgot about it, sorry.

**Comment by AdmiringWorm** [comment]
@majkinetor 
Is there anything else?

**Comment by majkinetor** [comment]
[Looks clear](https://www.youtube.com/watch?v=YVFgI_F4R7Y)

**Pull request merged**
