### PR TITLE
(thunderbird) Migrated to AU [AU thunderbird firefox]

### PR DESCRIPTION
**Pull request by AdmiringWorm**
when this is accepted, both this package and firefox can be pushed

### CODE REVIEW

**Comment by majkinetor** [comment]
Is it possible that both packages use the same helpers ? Perhaps thunderbird can use Firefox stuff or vice versa, its not really important. 

That would make maintenance much easier. 

My plan is to hae packages be as DRY as possible, for example https://github.com/majkinetor/au/issues/53 should accomplish similar stuff just on nuspec leel.

**Comment by gep13** [comment]
@AdmiringWorm you happy for me to merge, or are you planning on implementing above?

**Comment by gep13** [comment]
Seemed to me like they already were using same helper.

**Comment by majkinetor** [comment]
> Seemed to me like they already were using same helper.

Not sourcing the same file. Any future modifications will have to be done on 2 places.

**Comment by AdmiringWorm** [comment]
@majkinetor what are you talking about?
they are using the same helpers.

**Comment by majkinetor** [comment]
I must be insane. Sorry.

**Comment by AdmiringWorm** [comment]
no worries, we all have moments of insanity 😉 

anyways, if there are nothing else?
then I'm going to merge this

**Pull request merged**
