### PR TITLE
(firefox) Migrated to AU +++

### PR DESCRIPTION
**Pull request by AdmiringWorm**
I tried to make this generic enough so it can eventually be reused by the thunderbird package.

### CODE REVIEW

**Comment by majkinetor** [comment]
That was quite an effort!

**Comment by majkinetor** [comment]
LGTM

**Comment by majkinetor** [comment]
One thing is troublening me tho. I see you have non search and replace related code in `au_SearchReplace`. It would be more correct to move it to `au_BeforeUpdate`.

**Comment by AdmiringWorm** [comment]
good call, I definitely should move the the checksum file creation to afterupdate.
I'm on my way out to shovel some snow, but I'll take a look it when I'm done.

**Comment by majkinetor** [comment]
Snow... mmmm.

**Comment by AdmiringWorm** [comment]
@majkinetor could you review the latest changes?

**Comment by majkinetor** [comment]
Why do you have fixed version in installer (50.0) ? You could use $Env:ChocolateyPackageVersion ?

Otherwise looks good.

**Comment by AdmiringWorm** [comment]
if I use `$env:ChocolateyPackageVersion` that would also include the package fix version, and that won't work.
And since it is already being replaced in searchandreplace function, it doesn't matter if it is a fixed version or not.

**Comment by majkinetor** [comment]
Didn't think about that, you are right.

**Comment by AdmiringWorm** [comment]
I merged it now, I didn't push it though.
Plan to do that at the same time as when the thunderbird package is finished.

**Comment by majkinetor** [comment]
> if I use $env:ChocolateyPackageVersion that would also include the package fix version, and that won't work.

I came to say it doesn't matter as AU will change the version to fix one but I see now that you use `RemoteVersion` for that. I guess that few other packages have this 'fix' problem.

**Pull request merged**
