### PR TITLE
Sysinternals

### PR DESCRIPTION
**Pull request by majkinetor**

### CODE REVIEW

**Comment by majkinetor** [comment]
Not sure if so big description will pass on gallery.

**Comment by majkinetor** [comment]
```
PS> Test-Package

Package info
  Path:         C:\work\_chocolatey\chocolatey-coreteampackages\automatic\sysinternals\sysinternals.2016.11.18.20161217.nupkg
  Name:         sysinternals
  Version:      2016.11.18.20161217
  Vagrant:      c:\work\_chocolatey\chocolatey-test-environment

Testing package using vagrant
Removing existing vagrant packages
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ferventcoder/win2012r2-x64-nocm' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
==> default: Running: shell/TestPackages.ps1 as c:\tmp\vagrant-shell.ps1
==> default: ============================================================
==> default: TESTING FOLLOWING PACKAGES: sysinternals:2016.11.18.20161217
==> default: ============================================================
==> default: 
==> default: ------------------------------------------------------------
==> default: PACKAGE: sysinternals:2016.11.18.20161217
==> default: 
==> default: OPTIONS: c:\packages\sysinternals.2016.11.18.20161217.xml
==> default: 
==> default: Name                           Value                                           
==> default: ----                           -----                                           
==> default: Install                        True                                            
==> default: Uninstall                      False                                           
==> default: Parameters                                                                     
==> default: ------------------------------------------------------------ 
==> default: 
==> default: TESTING INSTALL FOR sysinternals:2016.11.18.20161217
==> default: CMD: choco install -fy sysinternals --allow-downgrade --version 2016.11.18.20161217 --source "'c:\packages;http://chocolatey.org/api/v2/'"
==> default: Chocolatey v0.10.3
==> default: Installing the following packages:
==> default: sysinternals
==> default: By installing you accept licenses for the packages.
==> default: 
==> default: sysinternals v2016.11.18.20161217 (forced)
==> default: sysinternals package files install completed. Performing other installation steps.
==> default: Sysinternals Suite is going to be installed in 'C:\ProgramData\chocolatey\lib\sysinternals\tools'
==> default: Downloading sysinternals 64 bit
==> default: 
==> default:   from 'https://download.sysinternals.com/files/SysinternalsSuite.zip'
==> default: 
==> default: Progress: 100% - Completed download of C:\Users\Administrator\AppData\Local\Temp\chocolatey\sysinternals\2016.11.18.20161217\SysinternalsSuite.zip (21.21 MB).
==> default: Download of SysinternalsSuite.zip (21.21 MB) completed.
==> default: Hashes match.
==> default: 
==> default: Extracting C:\Users\Administrator\AppData\Local\Temp\chocolatey\sysinternals\2016.11.18.20161217\SysinternalsSuite.zip to C:\ProgramData\chocolatey\lib\sysinternals\tools...
==> default: C:\ProgramData\chocolatey\lib\sysinternals\tools
==> default:  ShimGen has successfully created a shim for accesschk.exe
==> default:  ShimGen has successfully created a shim for accesschk64.exe
==> default:  ShimGen has successfully created a shim for AccessEnum.exe
==> default:  ShimGen has successfully created a shim for ADExplorer.exe
==> default:  ShimGen has successfully created a shim for ADInsight.exe
==> default:  ShimGen has successfully created a shim for adrestore.exe
==> default:  ShimGen has successfully created a shim for Autologon.exe
==> default:  ShimGen has successfully created a shim for Autoruns.exe
==> default:  ShimGen has successfully created a shim for Autoruns64.exe
==> default:  ShimGen has successfully created a shim for autorunsc.exe
==> default:  ShimGen has successfully created a shim for autorunsc64.exe
==> default:  ShimGen has successfully created a shim for Bginfo.exe
==> default:  ShimGen has successfully created a shim for Cacheset.exe
==> default:  ShimGen has successfully created a shim for Clockres.exe
==> default:  ShimGen has successfully created a shim for Clockres64.exe
==> default:  ShimGen has successfully created a shim for Contig.exe
==> default:  ShimGen has successfully created a shim for Contig64.exe
==> default:  ShimGen has successfully created a shim for Coreinfo.exe
==> default:  ShimGen has successfully created a shim for ctrl2cap.exe
==> default:  ShimGen has successfully created a shim for Dbgview.exe
==> default:  ShimGen has successfully created a shim for Desktops.exe
==> default:  ShimGen has successfully created a shim for disk2vhd.exe
==> default:  ShimGen has successfully created a shim for diskext.exe
==> default:  ShimGen has successfully created a shim for diskext64.exe
==> default:  ShimGen has successfully created a shim for Diskmon.exe
==> default:  ShimGen has successfully created a shim for DiskView.exe
==> default:  ShimGen has successfully created a shim for du.exe
==> default:  ShimGen has successfully created a shim for du64.exe
==> default:  ShimGen has successfully created a shim for efsdump.exe
==> default:  ShimGen has successfully created a shim for FindLinks.exe
==> default:  ShimGen has successfully created a shim for FindLinks64.exe
==> default:  ShimGen has successfully created a shim for handle.exe
==> default:  ShimGen has successfully created a shim for handle64.exe
==> default:  ShimGen has successfully created a shim for hex2dec.exe
==> default:  ShimGen has successfully created a shim for hex2dec64.exe
==> default:  ShimGen has successfully created a shim for junction.exe
==> default:  ShimGen has successfully created a shim for junction64.exe
==> default:  ShimGen has successfully created a shim for ldmdump.exe
==> default:  ShimGen has successfully created a shim for Listdlls.exe
==> default:  ShimGen has successfully created a shim for Listdlls64.exe
==> default:  ShimGen has successfully created a shim for livekd.exe
==> default:  ShimGen has successfully created a shim for livekd64.exe
==> default:  ShimGen has successfully created a shim for LoadOrd.exe
==> default:  ShimGen has successfully created a shim for LoadOrd64.exe
==> default:  ShimGen has successfully created a shim for LoadOrdC.exe
==> default:  ShimGen has successfully created a shim for LoadOrdC64.exe
==> default:  ShimGen has successfully created a shim for logonsessions.exe
==> default:  ShimGen has successfully created a shim for logonsessions64.exe
==> default:  ShimGen has successfully created a shim for movefile.exe
==> default:  ShimGen has successfully created a shim for movefile64.exe
==> default:  ShimGen has successfully created a shim for notmyfault.exe
==> default:  ShimGen has successfully created a shim for notmyfault64.exe
==> default:  ShimGen has successfully created a shim for notmyfaultc.exe
==> default:  ShimGen has successfully created a shim for notmyfaultc64.exe
==> default:  ShimGen has successfully created a shim for ntfsinfo.exe
==> default:  ShimGen has successfully created a shim for ntfsinfo64.exe
==> default:  ShimGen has successfully created a shim for pagedfrg.exe
==> default:  ShimGen has successfully created a shim for pendmoves.exe
==> default:  ShimGen has successfully created a shim for pendmoves64.exe
==> default:  ShimGen has successfully created a shim for pipelist.exe
==> default:  ShimGen has successfully created a shim for pipelist64.exe
==> default:  ShimGen has successfully created a shim for portmon.exe
==> default:  ShimGen has successfully created a shim for procdump.exe
==> default:  ShimGen has successfully created a shim for procdump64.exe
==> default:  ShimGen has successfully created a shim for procexp.exe
==> default:  ShimGen has successfully created a shim for procexp64.exe
==> default:  ShimGen has successfully created a shim for Procmon.exe
==> default:  ShimGen has successfully created a shim for PsExec.exe
==> default:  ShimGen has successfully created a shim for PsExec64.exe
==> default:  ShimGen has successfully created a shim for psfile.exe
==> default:  ShimGen has successfully created a shim for psfile64.exe
==> default:  ShimGen has successfully created a shim for PsGetsid.exe
==> default:  ShimGen has successfully created a shim for PsGetsid64.exe
==> default:  ShimGen has successfully created a shim for PsInfo.exe
==> default:  ShimGen has successfully created a shim for PsInfo64.exe
==> default:  ShimGen has successfully created a shim for pskill.exe
==> default:  ShimGen has successfully created a shim for pskill64.exe
==> default:  ShimGen has successfully created a shim for pslist.exe
==> default:  ShimGen has successfully created a shim for pslist64.exe
==> default:  ShimGen has successfully created a shim for PsLoggedon.exe
==> default:  ShimGen has successfully created a shim for PsLoggedon64.exe
==> default:  ShimGen has successfully created a shim for psloglist.exe
==> default:  ShimGen has successfully created a shim for pspasswd.exe
==> default:  ShimGen has successfully created a shim for pspasswd64.exe
==> default:  ShimGen has successfully created a shim for psping.exe
==> default:  ShimGen has successfully created a shim for psping64.exe
==> default:  ShimGen has successfully created a shim for PsService.exe
==> default:  ShimGen has successfully created a shim for PsService64.exe
==> default:  ShimGen has successfully created a shim for psshutdown.exe
==> default:  ShimGen has successfully created a shim for pssuspend.exe
==> default:  ShimGen has successfully created a shim for pssuspend64.exe
==> default:  ShimGen has successfully created a shim for RAMMap.exe
==> default:  ShimGen has successfully created a shim for RegDelNull.exe
==> default:  ShimGen has successfully created a shim for RegDelNull64.exe
==> default:  ShimGen has successfully created a shim for regjump.exe
==> default:  ShimGen has successfully created a shim for RootkitRevealer.exe
==> default:  ShimGen has successfully created a shim for ru.exe
==> default:  ShimGen has successfully created a shim for ru64.exe
==> default:  ShimGen has successfully created a shim for sdelete.exe
==> default:  ShimGen has successfully created a shim for sdelete64.exe
==> default:  ShimGen has successfully created a shim for ShareEnum.exe
==> default:  ShimGen has successfully created a shim for ShellRunas.exe
==> default:  ShimGen has successfully created a shim for sigcheck.exe
==> default:  ShimGen has successfully created a shim for sigcheck64.exe
==> default:  ShimGen has successfully created a shim for streams.exe
==> default:  ShimGen has successfully created a shim for streams64.exe
==> default:  ShimGen has successfully created a shim for strings.exe
==> default:  ShimGen has successfully created a shim for strings64.exe
==> default:  ShimGen has successfully created a shim for sync.exe
==> default:  ShimGen has successfully created a shim for sync64.exe
==> default:  ShimGen has successfully created a shim for Sysmon.exe
==> default:  ShimGen has successfully created a shim for Sysmon64.exe
==> default:  ShimGen has successfully created a shim for Tcpvcon.exe
==> default:  ShimGen has successfully created a shim for Tcpview.exe
==> default:  ShimGen has successfully created a shim for Testlimit.exe
==> default:  ShimGen has successfully created a shim for Testlimit64.exe
==> default:  ShimGen has successfully created a shim for vmmap.exe
==> default:  ShimGen has successfully created a shim for Volumeid.exe
==> default:  ShimGen has successfully created a shim for Volumeid64.exe
==> default:  ShimGen has successfully created a shim for whois.exe
==> default:  ShimGen has successfully created a shim for whois64.exe
==> default:  ShimGen has successfully created a shim for Winobj.exe
==> default:  ShimGen has successfully created a shim for ZoomIt.exe
==> default: 
==> default:  The install of sysinternals was successful.
==> default:   Software installed to 'C:\ProgramData\chocolatey\lib\sysinternals\tools'
==> default: Chocolatey installed 1/1 packages. 0 packages failed.
==> default:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
==> default: Exit code for sysinternals:2016.11.18.20161217 was 0
==> default: Running provisioner: shell...
    default: Running: User.ps1 as c:\tmp\vagrant-shell.ps1
==> default: User script can be added in User.ps1
==> default: 
==> default: SUCCESS: Specified value was saved.
==> default: Testing package if a line is uncommented.
==> default: 
==> default: Exit code was 0

```

**Comment by majkinetor** [comment]
```
PS> Test-Package -Parameters '/InstallDir:c:\tools\sysinternals'

Package info
  Path:         C:\work\_chocolatey\chocolatey-coreteampackages\automatic\sysinternals\sysinternals.2016.11.18.20161217.nupkg
  Name:         sysinternals
  Version:      2016.11.18.20161217
  Parameters:   /InstallDir:c:\tools\sysinternals
  Vagrant:      c:\work\_chocolatey\chocolatey-test-environment

Testing package using vagrant
Removing existing vagrant packages
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ferventcoder/win2012r2-x64-nocm' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: shell/TestPackages.ps1 as c:\tmp\vagrant-shell.ps1
==> default: ============================================================
==> default: TESTING FOLLOWING PACKAGES: sysinternals:2016.11.18.20161217
==> default: ============================================================
==> default: 
==> default: ------------------------------------------------------------
==> default: PACKAGE: sysinternals:2016.11.18.20161217
==> default: 
==> default: OPTIONS: c:\packages\sysinternals.2016.11.18.20161217.xml
==> default: 
==> default: Name                           Value                                           
==> default: ----                           -----                                           
==> default: Install                        True                                            
==> default: Uninstall                      False                                           
==> default: Parameters                     /InstallDir:c:\tools\sysinternals               
==> default: ------------------------------------------------------------ 
==> default: TESTING INSTALL FOR sysinternals:2016.11.18.20161217
==> default: 
==> default: CMD: choco install -fy sysinternals --allow-downgrade --version 2016.11.18.20161217 --source "'c:\packages;http://chocolatey.org/api/v2/'"  --params '/InstallDir:c:\tools\sysinternals'
==> default: Chocolatey v0.10.3
==> default: Installing the following packages:
==> default: 
==> default: sysinternals
==> default: By installing you accept licenses for the packages.
==> default: sysinternals v2016.11.18.20161217 (forced)
==> default: sysinternals package files install completed. Performing other installation steps.
==> default: Sysinternals Suite is going to be installed in 'c:\tools\sysinternals'
==> default: Downloading sysinternals 64 bit
==> default: 
==> default:   from 'https://download.sysinternals.com/files/SysinternalsSuite.zip'
==> default: Download of SysinternalsSuite.zip (21.21 MB) completed.
==> default: Hashes match.
==> default: Extracting C:\Users\Administrator\AppData\Local\Temp\chocolatey\sysinternals\2016.11.18.20161217\SysinternalsSuite.zip to c:\tools\sysinternals...
==> default: c:\tools\sysinternals
==> default: Adding to PATH if needed
==> default: PATH environment variable does not have c:\tools\sysinternals in it. Adding...
==> default: Environment Vars (like PATH) have changed. Close/reopen your shell to
==> default: 
==> default:  see the changes (or in powershell/cmd.exe just type `refreshenv`).
==> default:  The install of sysinternals was successful.
==> default: 
==> default:   Software installed to 'c:\tools\sysinternals'
==> default: Chocolatey installed 1/1 packages. 0 packages failed.
==> default:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
==> default: Exit code for sysinternals:2016.11.18.20161217 was 0

```

**Comment by majkinetor** [comment]
I would also switch default directory installation to be `Get-ToolsLocation` but I think @ferventcoder was against that previously, so I will wait for https://github.com/chocolatey/choco/issues/797 to get implemented.

**Comment by ferventcoder** [comment]
Where do I send feedback for Test-Package (don't use `--force`, it's an anti-pattern, use sahara and bring the box up to a sandbox, then reset to that snapshot before running each Test-Package).

**Comment by ferventcoder** [comment]
Although the force thing may be in the original test environment notes. I think that is there so you can continually force the test to clear out the original and reinstall with new packaging changes. In your case you don't need it, because you can reset each time.

**Comment by ferventcoder** [comment]
Looks like the install is also being forced here - https://github.com/chocolatey/package-verifier/blob/5b02947249bb2f5dd45ca1b78d5fc42d2bc7d9bb/src/chocolatey.package.verifier/infrastructure.app/tasks/TestPackageTask.cs#L103

Okay, I rescind the force for install. 👍 

Just ensure upgrade and uninstall do not use it.

**Comment by majkinetor** [comment]
Automatic rollback is planned as an option later to Tast-Package. It will not be used by default as it is destructive and that may not be what everybody wants.

Besides, rolling back each time adds aditional time (10-20 seconds) and its not handy with quick sequence of tests.

**Comment by AdmiringWorm** [comment]
Other than the description being way too long (maximum 4000 chars), this looks good to go.

**Pull request merged**
