### PR TITLE
KeePassX autopackage

### PR DESCRIPTION
**Pull request by Redsandro**
@gep13 This is also an old static package turned autopackage because updates were requested.
This one should be straightforward because the download is direct (no mirrors) and the installer is just a .zip.

### CODE REVIEW

**Comment by gep13** [comment]
When trying to load the ketarin xml file, I am getting this:

image

Can you correct?  I can't see anything obviously wrong, but perhaps I am looking in the wrong place.

**Comment by gep13** [comment]
@Redsandro ^^

**Comment by Redsandro** [comment]
@gep13 sorry, I can't see what I did wrong. So I took a different (working) xml and merged the `keepassx` settings. Can you verify if it imports now?

**Comment by gep13** [comment]
@Redsandro yes, that seems to work :+1:

**Pull request merged**
