### PR TITLE
clover: checksum incorrect

### PR DESCRIPTION
**Pull request by jmbeach**

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
@jmbeach I'm afraid that PRs which only changes the checksum and nothing else usually isn't accepted here.
The checksum is handled by AU (Chocolatey Automatic Package Updater Module) and will automatically be replaced when a new build run is initiated (in this case a forced run is needed).

I'll initiate a new forced update run on this package quite soon.

**Comment by jmbeach** [comment]
Gotcha. Didn't know that, sorry.

**Comment by jmbeach** [comment]
@AdmiringWorm, you merged my commit. Was that on accident?

**Comment by AdmiringWorm** [comment]
@jmbeach nah, it wasn't on accident.
I just used your PR to force the update of the clover package instead of pushing it manually from my local computer.

**Pull request merged**
