### PR TITLE
(mkdocs-material) Migrate Mkdocs material theme

### PR DESCRIPTION
**Pull request by pascalberger**
This PR is to move the MkDocs Material Theme package from https://github.com/BBTSoftwareAG/chocolatey-packages to the Core Team Packages.

I invited the Chocolatey user as a maintainer.

### CODE REVIEW

**Comment by majkinetor** [comment]
LGTM

**Comment by majkinetor** [comment]
As usual, feedback is needed upon removal of package from existing automation procedures.

**Comment by pascalberger** [comment]
@majkinetor I removed the packages / AU script from the original repo

**Comment by gep13** [comment]
Chocolatey user has been added to the package.

**Pull request merged**
