### PR TITLE
cyg-get: removed mirror url

### PR DESCRIPTION
**Pull request by Ferk**
It's not required to provide a mirror url for cywinsetup.exe, specially if cygwin was already installed and the settings from the installation are kept (which is a requirement for cyg-get already, anyway).

Simply removing it would work.

Alternativelly, you could get a mirror at random (or based on location if possible) from: https://cygwin.com/mirrors.lst

But please don't pick the US California mirror like this making it the forced default. Right now it's quite slow from where I'm in.

### CODE REVIEW

**Comment by ferventcoder** [comment]
Can you rebase this?

**Comment by Ferk** [comment]
Rebased

**Comment by ferventcoder** [comment]
Thanks!

**Comment by gep13** [comment]
@ferventcoder did you want to push a new version of this package?

**Comment by ferventcoder** [comment]
Yes please.

**Pull request merged**
