### PR TITLE
(lockhunter) migrated from ferventcoder [Requires chocolatey]

### PR DESCRIPTION
**Pull request by majkinetor**
https://github.com/ferventcoder/chocolatey-packages/pull/221

No open remote issues.

### CODE REVIEW

**Comment by majkinetor** [comment]
```
==> default: ============================================================
==> default: TESTING FOLLOWING PACKAGES: lockhunter:3.1
==> default: ============================================================
==> default:
==> default: ------------------------------------------------------------
==> default: PACKAGE: lockhunter:3.1
==> default: OPTIONS: c:\packages\lockhunter.3.1.xml
==> default:
==> default:
==> default: Name                           Value
==> default: ----                           -----
==> default: Install                        True
==> default: Uninstall                      False
==> default: Parameters
==> default: ------------------------------------------------------------
==> default:
==> default: TESTING INSTALL FOR lockhunter:3.1
==> default: CMD: choco install -fy lockhunter --allow-downgrade --version 3.1 --source "'c:\packages;http://chocolatey.org/api/v2/'"
==> default: Chocolatey v0.10.3
==> default: Installing the following packages:
==> default:
==> default: lockhunter
==> default: By installing you accept licenses for the packages.
==> default: lockhunter v3.1 (forced)
==> default: lockhunter package files install completed. Performing other installation steps.
==> default: Downloading lockhunter 64 bit
==> default:
==> default:   from 'http://lockhunter.com/exe/lockhuntersetup_3-1-1.exe'
==> default: Download of lockhuntersetup_3-1-1.exe (2.89 MB) completed.
==> default: Hashes match.
==> default:
==> default: Installing lockhunter...
==> default: lockhunter has been installed.
==> default: lockhunter installed to 'C:\Program Files\LockHunter'
==> default: lockhunter registered as lockhunter
==> default:  The install of lockhunter was successful.
==> default:
==> default:   Software installed to 'C:\Program Files\LockHunter\'
==> default: Chocolatey installed 1/1 packages. 0 packages failed.
==> default:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
==> default: Exit code for lockhunter:3.1 was 0

**Comment by gep13** [comment]
Associated Pull Request in @ferventcoder repository: https://github.com/ferventcoder/chocolatey-packages/pull/221

**Comment by gep13** [comment]
`chocolatey` user has been added to this package.

**Comment by gep13** [comment]
@majkinetor the associated PR has been merged into @ferventcoder repository.

**Comment by majkinetor** [comment]
Now also registers app so we could use it from console: `lockhunter -u $pwd`.

**Pull request merged**
