### PR TITLE
Added checksum for autohotkey.portable

### PR DESCRIPTION
**Pull request by Elderry**

### CODE REVIEW

**Comment by ferventcoder** [comment]
This is an auto package. It will need to be fixed in the ketarin job unless you are fixing the last version in the _output folder. HTH

**Comment by Elderry** [comment]
Is there any tutorial for ketarin xml jobs? I went to ketarin.org and found almost everything is about the software itself.

**Comment by ferventcoder** [comment]
@Elderry we have it all here https://github.com/chocolatey/chocolatey-packages-template and https://chocolatey.org/docs/automatic-packages

**Comment by Elderry** [comment]
Now I have a problem: If one package has both 32-bit and 64-bit version, how can I use one Ketarin job to download them all and then use ChocoPkgUp to get the checksum of these files? Is AU a better approach according to this condition?

**Comment by ferventcoder** [comment]
@Elderry the template already handles both. It's a pretty normal thing to see a package with both 32 and 64bit  urls.

**Comment by Elderry** [comment]
Sent a [new PR](https://github.com/chocolatey/chocolatey-coreteampackages/pull/299) to replace this one.

**Pull request closed without merging**
