### PR TITLE
Added djv and cutepdf

### PR DESCRIPTION
**Pull request by Redsandro**
Retry https://github.com/chocolatey/chocolatey-coreteampackages/pull/29 on clean checkout

### CODE REVIEW

**Comment by gep13** [comment]
@Redsandro is the icon that you have added for djv the correct one?  It looks more like a screenshot of the application, rather than an icon.  Thanks!

**Comment by Redsandro** [comment]
Yeah but no but yeah, I cannot find an icon. Perhaps it has no icon. But I hate it when things hate that blue icon that reeks like lazy package maintenance. So a miniature screenshot seemed like a good idea. Feel free to remove or change. But if you remove, don't expect a pat on the back from me. :smiling_imp:

**Comment by gep13** [comment]
@Redsandro how about this one:

djv

Extracted from the djv_view.exe:

image

using BeCyIconGrabber, as documented in the create packages wiki article:

https://github.com/chocolatey/chocolatey/wiki/CreatePackages#package-icon-guidelines

:+1:

**Comment by Redsandro** [comment]
Sure, use that one. :)

**Comment by gep13** [comment]
@Redsandro I have just tried to add your DJV ketarin file to the Ketarin instance, and I was met with this:

image

Can you please let me know the best approach to correct this?

Thanks!

**Comment by Redsandro** [comment]
Oh dear. How do the other sourceforge packages do this? I believe something like this used to work. Do the others still work?

**Comment by gep13** [comment]
In all honesty, I have no idea.  This would be a question for @tomone.  I have never made an automatic package that targets SourceForge.

**Comment by Redsandro** [comment]
Yeah, yeah I'm positive this used to work.

I think this needs to be addressed chocolatey-wide. See https://github.com/chocolatey/chocolatey/wiki/AutomaticPackages#important-notes-for-files-hosted-on-sourceforge

**Pull request merged**
