### PR TITLE
New package: Absolute uninstaller

### PR DESCRIPTION
**Pull request by Redsandro**
Absolute Uninstaller. I see the kids use this instead of Revo Uninstaller.

### CODE REVIEW

**Comment by ferventcoder** [comment]
I didn't realize this was a too

**Comment by Redsandro** [comment]
Not sure what you mean. You mean you didn't know this software before?

**Comment by ferventcoder** [comment]
never heard of it. I thought you had me something that would absolutely uninstall software.

**Comment by Redsandro** [comment]
Hahah :smile: sorry to disappoint.

This helps when you fix someones computer and you're like "omg wth did they install". It's still annoying but a bit less.

**Comment by Redsandro** [comment]
@gep13 @TomOne I think this can be safely merged, but it needs to be put in the mamebapma.

**Comment by Redsandro** [comment]
(master mega batch processing machine)

**Pull request merged**
