### PR TITLE
Added Korean and Turkish language

### PR DESCRIPTION
**Pull request by Redsandro**

### CODE REVIEW

**Comment by gep13** [comment]
Yip, I will try to get to this at the weekend.

**Comment by gep13** [comment]
@TomOne @Redsandro I am really sorry, I messed up merging this pull request in, apologies :crying_cat_face: 

This PR has been merged in though.

**Comment by gep13** [comment]
New package pushed:

https://chocolatey.org/packages/tor-browser/4.0.2.20150109

**Comment by Redsandro** [comment]
I don't know what you mean you messed up. This looks fine! :+1:

**Comment by gep13** [comment]
This extra [merge](https://github.com/chocolatey/chocolatey-coreteampackages/commit/cd459f490f3018e78c9c46435a7800aa46c88829) shouldn't really be here :smile:

**Comment by Redsandro** [comment]
If it works. :)

**Comment by gep13** [comment]
> If it works. :)

There is something to that :-D

**Pull request closed without merging**
